#!/usr/bin/zsh
RESET="\033[m"
RED_FG="\033[31m"
GREEN_FG="\033[32m"
YELLOW_FG="\033[33m"
BLUE_FG="\033[34m"
MAGENTA_FG="\033[35m"
CYAN_FG="\033[36m"
WHITE_FG="\033[37m"
BOLD="\033[1m"

nmcli con mod MOVISTAR_134D ipv4.addresses 192.168.8.100/24
nmcli con mod MOVISTAR_134D ipv4.gateway 192.168.8.1
nmcli con mod MOVISTAR_134D ipv4.dns 8.8.8.8
nmcli con mod MOVISTAR_134D ipv4.method manual
