#!/usr/bin/zsh
RESET="\033[m"
RED_FG="\033[31m"
GREEN_FG="\033[32m"
YELLOW_FG="\033[33m"
BLUE_FG="\033[34m"
MAGENTA_FG="\033[35m"
CYAN_FG="\033[36m"
WHITE_FG="\033[37m"

gsettings set org.gnome.shell.extensions.dash-to-dock show-apps-at-top true
echo show-apps-at-top=true >> /usr/share/glib-2.0/schemas/10_ubuntu-dock.gschema.override
glib-compile-schemas /usr/share/glib-2.0/schemas/
