#!/usr/bin/zsh
#vim: syntax off
BOLD="\033[1m"
RESET="\033[m"
BOLD="\033[1m"
ITALIC="\033[3m"
UNDER="\033[4m"
REVERSE="\033[7m"
STRIKE="\033[9m"
RED_FG="\033[31m"
GREEN_FG="\033[32m"
YELLOW_FG="\033[33m"
BLUE_FG="\033[34m"
MAGENTA_FG="\033[35m"
CYAN_FG="\033[36m"
WHITE_FG="\033[37m"

#Declarations
typeset -a _SOURCES
typeset -aU _TODO_LIST
typeset -A _SEEN
typeset GET_PWD=true

#Constants
_THIS=${0:t}
CACHED_TARGETS=~/.tvi/cached_targets
_SOURCES+=${PWD}
_SOURCES+="/usr/local/bin"
_SOURCES+="/usr/local/bin/system"
_SOURCES+="/usr/local/lib"
_SOURCES+="/home/kmiller/Code/LOCAL"

#Imports
_LIB_DIR=/usr/local/lib
source ${_LIB_DIR}/LIB_INIT.zsh
source ${_LIB_DIR}/STR.zsh

for D in ${=_DEPS_};do
	if [[ -e ${_LIB_DIR}/${D} ]];then
		source ${_LIB_DIR}/${D}
	else
		echo "Cannot source:${_LIB_DIR}/${D} - not found"
		exit 1
	fi
done

read -r -d '' DESC<<EOF
Show list of TODO labels embedded in scripts
EOF

#Functions
usage () {
	local -a PENDING_MSGS=(${@})

	tabs 5
	[[ ${_SMCUP} == 'true' ]] && do_rmcup

	(
	echo "Usage: ${_SCRIPT}"
	echo "${WHITE_FG}\nDesc${RESET}:${DESC}"
	) >&2

	exit_leave ${PENDING_MSGS}
}

#Execution
[[ ${1} == '-H' ]] && usage

echo "${CYAN_FG}${BOLD}Cached edits${WHITE_FG}...${RESET}"
while read F;do
	[[ ${F} =~ ${_THIS} ]] && continue
	FN=$(echo ${F} | cut -d \| -f2 2>/dev/null)
	[[ ${_SEEN[${FN}]} -eq 1 ]] && continue
	[[ ! -e ${FN} || ${FN:t} == ${_SCRIPT} ]] && continue
	grep -qP "#TODO" ${FN}
	if [[ $? -eq 0 ]];then
		_SEEN[${FN}]=1
		echo "File:${WHITE_FG}${FN}${RESET}"
		TXT=$(grep -P "#TODO" ${FN})
		TXT=$(echo ${TXT} | sed "s/TODO/$(echo ${WHITE_FG}${ITALIC})TODO$(echo ${RESET})$(echo ${MAGENTA_FG})/g")
		echo "${MAGENTA_FG}$(str_trim ${TXT})${RESET}\n"
	fi
done < ${CACHED_TARGETS}

GET_PWD=true
for S in ${(ou)_SOURCES};do
	_TODO_LIST+=("${(f)$(find ${S} -maxdepth 2 -type f)}")
	[[ ${S} == ${PWD} ]] && GET_PWD=false
done
[[ ${GET_PWD} == 'true' ]] && _TODO_LIST+=("${(f)$(find ${PWD} -maxdepth 2 -type f)}")

echo "${GREEN_FG}${BOLD}Local source and non cached${WHITE_FG}...${RESET}"
HIT=false
LAST_FN=?
for F in ${_TODO_LIST};do
	[[ ${_SEEN[${F}]} -eq 1 ]] && continue
	[[ ${F:e} == 'bak' || ${F:e} == 'orig' ]] && continue
	[[ ${F} =~ ${_THIS} ]] && continue
	[[ ! $(file -b ${F}) =~ 'zsh' && ! ${F:e} == 'zsh' ]] && continue
	[[ ! -r ${F} ]] && continue
 	grep -qP "#TODO" ${F}
 	if [[ $? -eq 0 ]];then
 		HIT=true
 		echo "File:${WHITE_FG}${F}${RESET}"
 		TXT=$(grep -P "#TODO" ${F})
 		TXT=$(echo ${TXT} | sed "s/TODO/$(echo ${WHITE_FG}${ITALIC})TODO$(echo ${RESET})$(echo ${MAGENTA_FG})/g")
 		echo "${MAGENTA_FG}$(str_trim ${TXT})${RESET}\n"
		_SEEN[${F}]=1
 	fi
done

[[ ${HIT} == 'false' ]] && echo "No todo tags found"

exit_leave
