#!/usr/bin/zsh
[[ ${1} == "-H" ]] && echo "Usage:${0}\n Desc:toggle autodock visibility"
gsettings set org.gnome.shell.extensions.dash-to-dock autohide false
gsettings set org.gnome.shell.extensions.dash-to-dock autohide true
