#!/usr/bin/zsh
#Inline ansi
BOLD="\033[1m"
ITALIC="\033[3m"
RESET="\033[m"
REVERSE="\033[7m"
STRIKE="\033[9m"
UNDER="\033[4m"

BLACK_BG="\033[40m"

BLUE_FG="\033[34m"
CYAN_FG="\033[36m"
GREEN_FG="\033[32m"
MAGENTA_FG="\033[35m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"
YELLOW_FG="\033[33m"

WHITE_ON_GREY="\033[0m\033[0;1;37;100m"

# Declarations
typeset -a ALIASES=()

# Constants
FN=/etc/zsh/aliases
HELP="${WHITE_FG}Usage${RESET}:\t${0:t} [-H] [SEARCHTERM]\n${WHITE_FG} Desc${RESET}:\tshow all or matching aliases separated by type\n\tSEARCHTERM matches leading chars of alias\n"

# Vars
SEARCHTERM=''

# Executions
[[ ${1} == '-H' ]] && echo ${HELP} && exit
[[ ${#} -ne 0 ]] && SEARCHTERM=${1}
[[ -n ${SEARCHTERM} ]] && TAG="${WHITE_FG}(${RESET}FILTER = \"${WHITE_FG}${SEARCHTERM}${RESET}\"${WHITE_FG})${RESET}" || TAG="${WHITE_FG}(${RESET}UNFILTERED${WHITE_FG})${RESET}"

while read LINE;do
	ALIASES+=${LINE}
done < ${FN}

(
echo "${BOLD}${CYAN_FG}List of Defined Aliases ${TAG}${RESET}\n"
echo "Directory Change"

HIT=false
for A in ${(o)ALIASES};do
	[[ ! ${A} =~ '=' ]] && continue
	[[ ! ${A} =~ 'cd' ]] && continue
	ABBV=$(cut -d'=' -f1 <<<${A} | sed 's/alias//')
	[[ -n ${SEARCHTERM} && ! ${ABBV} =~ "^\s+?${SEARCHTERM}.*" ]] && continue
	HIT=true
	CMD=$(cut -d'=' -f2 <<<${A} | sed -e "s/'//g" -e 's/"//g')
	printf "${CYAN_FG}%15s ${WHITE_FG}%-30s${RESET}\n" ${ABBV} ${CMD}
done
[[ ${HIT} == 'false' ]] && echo "\t${ITALIC}${RED_FG}FILTERED${RESET}"

echo "\nCommands"
HIT=false
for A in ${(o)ALIASES};do
	[[ ! ${A} =~ '=' ]] && continue
	[[ ${A} =~ 'cd' ]] && continue
	ABBV=$(cut -d'=' -f1 <<<${A} | sed 's/alias//')
	[[ -n ${SEARCHTERM} && ! ${ABBV} =~ "^\s+?${SEARCHTERM}.*" ]] && continue
	HIT=true
	CMD=$(cut -d'=' -f2 <<<${A} | sed -e "s/'//g" -e 's/"//g')
	printf "${CYAN_FG}%15s ${WHITE_FG}%-30s${RESET}\n" ${ABBV} ${CMD}
done
[[ ${HIT} == 'false' ]] && echo "\t${ITALIC}${RED_FG}FILTERED${RESET}"

) | mypager
