#!/usr/bin/zsh
#Inline ansi
BOLD="\033[1m"
ITALIC="\033[3m"
RESET="\033[m"
REVERSE="\033[7m"
STRIKE="\033[9m"
UNDER="\033[4m"

BLACK_BG="\033[40m"

BLUE_FG="\033[34m"
CYAN_FG="\033[36m"
GREEN_FG="\033[32m"
MAGENTA_FG="\033[35m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"
YELLOW_FG="\033[33m"

WHITE_ON_GREY="\033[0m\033[0;1;37;100m"

FN=/etc/zsh/aliases

typeset -a ALIASES=()

while read LINE;do
	ALIASES+=${LINE}
done < ${FN}


(
echo "${BOLD}${CYAN_FG}LIST OF DEFINED ALIASES${RESET}\n"
echo "DIRECTORY CHANGE"
for A in ${(o)ALIASES};do
	[[ ! ${A} =~ '=' ]] && continue
	[[ ! ${A} =~ 'cd' ]] && continue
	ABBV=$(cut -d'=' -f1 <<<${A} | sed 's/alias//')
	CMD=$(cut -d'=' -f2 <<<${A} | sed -e "s/'//g" -e 's/"//g')
	printf "${CYAN_FG}%10s ${WHITE_FG}%-30s${RESET}\n" ${ABBV} ${CMD}
done

echo "\nCOMMANDS"
for A in ${(o)ALIASES};do
	[[ ! ${A} =~ '=' ]] && continue
	[[ ${A} =~ 'cd' ]] && continue
	ABBV=$(cut -d'=' -f1 <<<${A} | sed 's/alias//')
	CMD=$(cut -d'=' -f2 <<<${A} | sed -e "s/'//g" -e 's/"//g')
	printf "${CYAN_FG}%10s ${WHITE_FG}%-30s${RESET}\n" ${ABBV} ${CMD}
done
) | mypager
