#!/usr/bin/zsh
REVERSE="\033[7m"
RESET="\033[m"
BOLD="\033[1m"
BLACK_FG="\033[30m"
RED_FG="\033[1;31m"
GREEN_FG="\033[1;32m"
YELLOW_FG="\033[1;33m"
BLUE_FG="\033[1;34m"
MAGENTA_FG="\033[1;35m"
CYAN_FG="\033[1;36m"
WHITE_FG="\033[1;37m"

STRIKE="\033[9m"
ITALIC="\033[3m"
UNDER="\033[4m"

E_REVERSE=$(echo "\033[7m")
E_RESET=$(echo "\033[m")
E_BOLD=$(echo "\033[1m")
E_BLACK_FG=$(echo "\033[30m")
E_RED_FG=$(echo "\033[31m")
E_GREEN_FG=$(echo "\033[32m")
E_YELLOW_FG=$(echo "\033[33m")
E_BLUE_FG=$(echo "\033[34m")
E_MAGENTA_FG=$(echo "\033[35m")
E_CYAN_FG=$(echo "\033[36m")
E_WHITE_FG=$(echo "\033[37m")
E_STRIKE=$(echo "\033[9m")

#Constants
[[ -e /usr/bin/flatpak ]] && _FLATPAK_INSTALLED=true || _FLATPAK_INSTALLED=false
[[ -e /usr/bin/snap ]] && _SNAP_INSTALLED=true || _SNAP_INSTALLED=false
_HDR_BAR=$'\u2501' #header character
_LAST_APT_UPD=~/.last_apt_upd
_LIB=/usr/local/lib
_SOURCES=/etc/apt/sources.list.d

#Imports
source ${_LIB}/common.zsh

#Declarations
typeset -A STATE
typeset -a LAST_MSG_COORDS=(-1 -1 -1 -1 -1)
typeset -a LIST
typeset -a MARKED
typeset -g ACTION_LOG=/tmp/search_action.log
typeset -g LASTPKG=none
typeset -g LONGEST_DESC
typeset -g LONGEST_NAME
typeset -g LONGEST_STATE
typeset -g MAX_DESC_LEN=70

#Globals
g_INFO_OPTION=false
g_INSTALL_OPTION=false
g_PURGE_OPTION=false
g_UNINSTALL_OPTION=false

#Functions
action_do () {
	local MARKED=${1}
	local PKG RC 
	local PKG_NAME 
	local PKG_STATE 
	local UPD_PKG_LIST

	[[ ${_DEBUG} -gt 0 ]] && dbg "${0}:ARGS:${@}"

	#Initialize
	PKG=${_LIST[${MARKED}]}
	PKG_NAME=$(get_package_name ${PKG})
	PKG_STATE=$(get_package_state ${PKG})
	UPD_PKG_LIST=true

	msg_box_clear

	if [[ ${g_INFO_OPTION} == 'true' || ${PKG_STATE:l} =~ "^[sf].*" ]];then
		msg_box -x10 "Retrieving info..."
		if [[ ${PKG_STATE:l} == "snap" && ${_SNAP_INSTALLED} == 'true' ]];then
			UPD_PKG_LIST=false
			msg_stream "snap info ${PKG_NAME} 2>/dev/null | tr -s '[:space:]'"
		elif [[ ${PKG_STATE:l} == "flatpak" && ${_FLATPAK_INSTALLED} == 'true'  ]];then 
			UPD_PKG_LIST=false
			msg_stream "flatpak info ${PKG_NAME} 2>/dev/null"
		else
			msg_stream "aptitude show ${PKG_NAME} 2>/dev/null"
		fi
	fi

	if [[ ${g_INFO_OPTION} == 'true' && ${PKG_STATE:l} =~ "^uninstalled*" ]];then
		msg_box -p -PI "Package: ${PKG_NAME}" #Option to install after view
		[[ ${_MSG_KEY} == 'y' ]] && g_INSTALL_OPTION=true
	fi

	if [[ ${g_UNINSTALL_OPTION} == 'true' && ${PKG_STATE:l} =~ "^installed*" ]];then
		msg_box "Uninstalling ${PKG_NAME}..."
		msg_stream "sudo apt-get -y remove ${PKG_NAME} 2>&1"
	elif [[ ${g_INSTALL_OPTION} == 'true' && ${PKG_STATE:l} =~ "^uninstalled*" ]];then
		msg_box "Installing ${PKG_NAME}..."
		msg_stream "sudo apt-get -y install ${PKG_NAME} 2>&1"
	elif [[ ${g_PURGE_OPTION} == 'true' && ${PKG_STATE:l} =~ "^config*" ]];then
		msg_box "Purging config for ${PKG_NAME}..."
		msg_stream "sudo apt-get -y purge ${PKG_NAME} 2>&1"
	else
		UPD_PKG_LIST=false
	fi

	[[ ${UPD_PKG_LIST} == 'true' ]] && upd_package_list ${PKG_NAME} ${MARKED}

	list_set_selected ${MARKED} 0
}

action_warn () {
	local MARKED=${1}
	local PKG_NAME
	local PKG_STATE
	local MSG PROMPT
	local ITEM
	local RC=0

	[[ ${_DEBUG} -gt 0 ]] && dbg "${0}:ARGS:${@}" 

	ITEM=${LIST[${MARKED}]}
	PKG_NAME=$(get_package_name ${ITEM})
	PKG_STATE=$(get_package_state ${ITEM})

	g_INSTALL_OPTION=false
	g_INFO_OPTION=false
	g_PURGE_OPTION=false
	g_UNINSTALL_OPTION=false
	g_INFO_OPTION=false

	if [[ ${PKG_STATE:l} =~ "^installed*" ]];then
		MSG='uninstalled'
		PROMPT='(U)ninstall or (V)iew Info'
	elif [[ ${PKG_STATE:l} =~ "^uninstalled*" ]];then
		MSG='installed'
		PROMPT='(I)nstall or (V)iew Info'
	elif [[ ${PKG_STATE:l} =~ "^config*" ]];then
		MSG='purged'
		PROMPT='(P)urge or (V)iew Info'
	elif [[ ${PKG_STATE:l} =~ "^snap*" ]];then
		MSG='queried for info'
		PROMPT='(V)iew Info'
	elif [[ ${PKG_STATE:l} =~ "^flat*" ]];then
		MSG='queried for info'
		PROMPT='(V)iew Info'
	else
		MSG=''
		PROMPT=''
	fi

	if [[ -z ${MSG} ]];then
		msg_box -p -PK "No action available for:${PKG_STATE}"
	else
		msg_box -p -P"${PROMPT} for package" "<I>Pending Action<N>|==============| |<B>${PKG_NAME}<N>|can be|<I>${MSG}<N>"
	fi

	case ${_MSG_KEY} in 
		n) RC=1;;
		i) g_INSTALL_OPTION=true;;
		p) g_PURGE_OPTION=true;;
		u) g_UNINSTALL_OPTION=true;;
		v) g_INFO_OPTION=true;;
	esac

	list_set_selected ${MARKED} 0

	return ${RC}
}

upd_package_list () {
	local PACKAGE=${1}
	local PKG_NDX=${2}
	local -a RAWLIST

	[[ ${_DEBUG} -gt 0 ]] && dbg "${0}:PACKAGE:${PACKAGE}, PKG_NDX:${PKG_NDX}"

	RAWLIST=("${(@f)$(aptitude search ${PACKAGE} -F '%c|%p|%d' 2>&1| grep "|${PACKAGE}|")}")

	[[ -z ${#RAWLIST} ]] && msg_box -p -PK "${RED_FG}WARNING${RESET}:Query returned no items"
	[[ ${#RAWLIST} -ne 1 ]] && msg_box -p -PK "${RED_FG}WARNING${RESET}:Query returned more than 1 item. Using first item"

	LIST[${PKG_NDX}]=${RAWLIST[1]}
}

set_package_list () {
	local -a PATTERN=($1)
	local -a RAWLIST
	local APP
	local APP_FPAK
	local APP_NAME
	local DESC
	local F L R S
	local FLATLIST
	local MATCH MBEGIN MEND
	local NDX
	local PKG_STATE
	local P_DESC
	local P_NAME
	local SHOW_FLAT
	local SHOW_SNAP
	local SNAPLIST

	[[ ${_DEBUG} -gt 0 ]] && dbg "${0}:ARGS:${@}"
	
	LIST=()
	MARKED=()

	#handle non distribution list
	if [[ ${SHOW_NOND} == "true" ]];then
		msg_box "Building list of packages added since OS was installed...please wait"
		LIST=("${(@f)$(non_distribution)}")
		for L in ${LIST};do
			P_NAME=$(echo ${L} | cut -d'|' -f2)
			P_DESC=$(echo ${L} | cut -d'|' -f3)
			[[ ${#P_NAME} -ge ${LONGEST_NAME} ]] && LONGEST_NAME=${#P_NAME}
			[[ ${#P_DESC} -ge ${LONGEST_DESC} ]] && LONGEST_DESC=${#P_DESC}
		done
		((LONGEST_NAME+=2))
		[[ ${LONGEST_DESC} -ge ${MAX_DESC_LEN} ]] && LONGEST_DESC=$((MAX_DESC_LEN+=2)) || ((LONGEST_DESC+=2))
		return
	fi

	#retrieve data from aptitude
	[[ ${_DEBUG} -gt 0 ]] && dbg "${0}: aptitude search ${PATTERN}"

	msg_box -x10 "Retrieving data from aptitude..."

	if [[ ${MATCH_DESC} == "true" ]];then
		RAWLIST=("${(@f)$(aptitude search ${PATTERN} -F '%c|%p|%d' | grep -i ${SEARCHTERM})}")
	else
		RAWLIST=("${(@f)$(aptitude search ${PATTERN} -F '%c|%p|%d')}")
	fi

	if [[ ${_DEBUG} -gt 1 ]];then
		dbg $(
		echo "\naptitude returned ${#RAWLIST} rows"
		for R in ${RAWLIST};do
			echo "${WHITE_FG}${R}${RESET}"
		done
		)
	fi
	
	if [[ ${SKIP_SNAPFLAT} == 'false' ]];then
		#snap and flatpak support
		[[ ${_DEBUG} -gt 0 ]] && echo "\nAdding packages from snap and flatpak..."

		if [[ ${SHOW_ALL_PKGS} == "true" || ${SHOW_INST} == "true" ]];then
			if [[ ${_SNAP_INSTALLED} == 'true' ]];then
				msg_box -x10 "Retrieving data from snap and flatpak..."
				SHOW_SNAP=true
				SNAPLIST=("${(f)$(snap list | tail +2)}")

				[[ ${_DEBUG} -gt 0 ]] && dbg "${0}:snap returned ${#SNAPLIST} rows"

				for S in ${SNAPLIST};do
					APP=$(echo ${S} | tr -s '[:space:]' | cut -d' ' -f1)
					DESC=$(snap info ${APP} | grep -i summary: | sed -e 's/summary://g' -e 's/^[ \t]*//g')
					[[ ${APP} =~ ${SEARCHTERM} || -z ${SEARCHTERM} ]] && RAWLIST+="s|${APP}|${DESC}"
				done
			fi
		
			if [[ ${_FLATPAK_INSTALLED} == 'true' ]];then
				SHOW_FLAT=true
				( FLATLIST=("${(f)$(flatpak list | tail +1)}") ) 2>/dev/null #flatpak warnings supressed

				[[ ${_DEBUG} -gt 0 ]] && dbg "${0}:flatpak returned ${#FLATLIST} rows"

				for F in ${FLATLIST};do
					APP_NAME=$(echo ${F} | tr -s '[:space:]' | cut -f1)
					APP_FPAK=$(echo ${F} | tr -s '[:space:]' | cut -f2)
					[[ ${_DEBUG} -gt 0 ]] && dbg "${0}:(flatpak) APP:${APP}"
					DESC=$(flatpak info ${APP_FPAK} | grep -i subject: | sed -e 's/subject://gi' -e 's/^[ \t]*//g')
					[[ ${APP_NAME} =~ ${SEARCHTERM} || -z ${SEARCHTERM} ]] && RAWLIST+="f|${APP_NAME}|${DESC}"
				done
			fi
		fi
	fi

	typeset -F ROWTIME=$(echo ${#RAWLIST}/9000 | bc -l)

	[[ ${_DEBUG} -gt 0 ]] && dbg "${0}:row count < 10000"

	if [[ ${#RAWLIST} -ge 10000 ]];then
		msg_box -p -PP "${BOLD}${#RAWLIST} is a lot of rows.${RESET} This could take $(printf "%.2f" ${ROWTIME}) minutes. HINT:add a search term to limit rows"
		if [[ ${_MSG_KEY} != 'y' ]];then
			exit_leave $(msg_warn "Operation cancelled")
		fi
	fi

	[[ ${_DEBUG} -gt 0 ]] && dbg "${0}:Processing RAWLIST"

	NDX=0
	for L in ${RAWLIST};do
		((NDX++))

		tput cup 0 0; printf "\rProcessing line ${WHITE_FG}%d${RESET} of ${WHITE_FG}%d${RESET} lines ${WHITE_FG}%%${BOLD}${GREEN_FG}%.2f${RESET}" ${NDX} ${#RAWLIST} $(( NDX * 100. / ${#RAWLIST} ))

		P_NAME=$(echo ${L} | cut -d'|' -f2)
		P_DESC=$(echo ${L} | cut -d'|' -f3)
		[[ ${#P_NAME} -ge ${LONGEST_NAME} ]] && LONGEST_NAME=${#P_NAME}
		[[ ${#P_DESC} -ge ${LONGEST_DESC} ]] && LONGEST_DESC=${#P_DESC}
		if [[ ${MATCH_DESC} == "true" ]];then
			if [[ ${FUZZY} == "false" ]];then
				[[ ${L:l} =~ "^${SEARCHTERM:l}" ]] && LIST+=${L}
			else
				[[ ${L:l} =~ "${SEARCHTERM:l}" ]] && LIST+=${L}
			fi
		else
			case ${L[1,1]} in
				s) [[ ${SHOW_SNAP} == "true" ]] && LIST+=${L};;
				f) [[ ${SHOW_FLAT} == "true" ]] && LIST+=${L};;
				c) [[ ${SHOW_CONF} == "true" ]] && LIST+=${L};;
				i) [[ ${SHOW_INST} == "true" ]] && LIST+=${L};;
				p) [[ ${SHOW_UNIN} == "true" || ${SHOW_UNIN_RECOM} == "true" ]] && LIST+=${L};;
				v) [[ ${SHOW_VIRT} == "true" ]] && LIST+=${L};;
			esac
		fi
	done

	((LONGEST_NAME+=2))
	[[ ${LONGEST_DESC} -ge ${MAX_DESC_LEN} ]] && LONGEST_DESC=$((MAX_DESC_LEN+=2)) || ((LONGEST_DESC+=2))
	[[ ${_DEBUG} -gt 0 ]] && dbg "${0}:LIST COUNT:${#LIST}"
}

get_package_state () {
	local P=${1}
	local PKG_STATE

	[[ ${_DEBUG} -gt 1 ]] && dbg "${0}:ARGS:${@}"

	case ${P[1,1]:l} in
		p*) PKG_STATE=Uninstalled;;
		c*) PKG_STATE=Config;;
		i*) PKG_STATE=Installed;;
		v*) PKG_STATE=Virtual;;
		s*) PKG_STATE=Snap;;
		f*) PKG_STATE=Flatpak;;
		*) PKG_STATE=Undefined; dbg "${0}:Undefined:${P:l} waiting..."
	esac
	echo ${PKG_STATE}
}

get_package_name () {
	local ITEM=${1}

	[[ ${_DEBUG} -gt 1 ]] && dbg "${0}:ARGS:${@}"

	echo ${ITEM} | cut -d'|' -f2
}

get_package_desc () {
	local ITEM=${1}

	[[ ${_DEBUG} -gt 1 ]] && dbg "${0}:ARGS:${@}"

	ITEM=$(echo ${ITEM} | cut -d'|' -f3)
	echo ${ITEM[1,${MAX_DESC_LEN}]}
}

set_state_color () {
	local STATE=${@}

	[[ ${_DEBUG} -gt 1 ]] && dbg "${0}:ARGS:${@}"

	if [[ ${STATE:l} =~ "^installed*" ]];then
		echo ${GREEN_FG}
	elif [[ ${STATE:l} =~ "^uninstalled*" ]];then
		echo ${RED_FG}${STRIKE}
	elif [[ ${STATE:l} =~ "^config*" ]];then
		echo ${ITALIC}${MAGENTA_FG}
	elif [[ ${STATE:l} =~ "^virtual*" ]];then
		echo ${CYAN_FG}
	elif [[ ${STATE:l} =~ "^snap*" ]];then
		echo "${ITALIC}${GREEN_FG}"
	elif [[ ${STATE:l} =~ "^flatpak*" ]];then
		echo "${ITALIC}${GREEN_FG}"
	else
		echo ${WHITE_FG}
	fi
}

non_distribution () {
	local PKGS=()
	local ARGLIST=()

	# DISTRIBUTION PACKAGES <(gzip -dc /var/log/installer/initial-status.gz | sed -n 's/^Package: //p' | sort -u))
	# INSTALLED PACKAGES <(aptitude search '~i !~M' -F '%p' | sed "s/ *$//" | sort -u) 
	# comm column1 produces a list of items not in both sets

	[[ ${_DEBUG} -gt 0 ]] && dbg "${0}:ARGS:${@}"

	echo "Retrieving packages..."
	PKGS=$(comm -23 <(aptitude search '~i !~M' -F '%p' | sed "s/ *$//" | sort -u) <(gzip -dc /var/log/installer/initial-status.gz | sed -n 's/^Package: //p' | sort -u))
	echo "${0}:${#PKGS} total packages found..."

	# pass each list item to aptitude to optain package description info
	echo "${0}:Building aptitude query..."
	NDX=0
	for P in ${=PKGS};do
		((NDX++))
		printf "\rProcessing:${WHITE_FG}%s${RESET} of ${#PKGS}" ${NDX}
		ARGLIST+="~n^${P}$"
	done
	echo "\nExecuting aptitude query for ${#ARGLIST} packages..."
	aptitude search "${=ARGLIST}" -F '%c|%p|%d' | grep -v i386 
}


#--Begin GetOpts--
read -r -d '' DESC<<EOF
Display apps installed or uninstalled
\tYou may supply either an option, a <SEARCHTERM>, or both
\t<SEARCHTERM> matches leading characters unless overridden
\tIf no arguments or options are supplied, all apps are displayed
EOF

usage () {
	local -a PENDING_MSGS=(${@})

	tabs 5
	[[ ${_SMCUP} == 'true' ]] && do_rmcup

	echo -e "Usage:${_SCRIPT} ${WHITE_FG}[${RESET}${OPTSTR}${WHITE_FG}]${RESET} ${WHITE_FG}[${RESET}PATTERN${WHITE_FG}]${RESET}\n"
	echo -e "-H help"
	echo -e "-D DEBUG"
	echo -e "-3 show i386 packages"
	echo -e "-c show only config-present (uninstalled)"
	echo -e "-d include package description in search"
	echo -e "-f write display contents to file"
	echo -e "-i show only installed"
	echo -e "-n show only packages not part of original OS distribution"
	echo -e "-r show only uninstalled and limit to recommended packages"
	echo -e "-s skip snap and flatpak"
	echo -e "-u show only uninstalled"
	echo -e "-v show only installed virtual (ignores architecture)"
	echo -e "-z fuzzy match (default is leading match)"
	echo -e "${WHITE_FG}\nDESC${RESET}:${DESC}"

	exit_leave ${PENDING_MSGS}
}

SHOW_ALL_PKGS=true
SHOW_INST=false
SHOW_UNIN=false
SHOW_UNIN_RECOM=false
SHOW_VIRT=false
SHOW_CONF=false
SHOW_NOND=false
SKIP_SNAPFLAT=false
TO_FILE=false
MATCH_DESC=false
PATTERN=?
OPTIND=0
I386=false
FUZZY=false
OBJTYPE="Package"

OPTSTR=":HD3cdfinrsuvz"

while getopts ${OPTSTR} opts;do
	case ${opts} in
     H) usage;;
     D) dbg_set_level;;
     3) I386=true;;
     c) SHOW_ALL_PKGS=false;SHOW_CONF=true;;
     d) MATCH_DESC=true;;
     f) TO_FILE=true;;
     i) SHOW_ALL_PKGS=false;SHOW_INST=true;;
     n) SHOW_ALL_PKGS=false;SHOW_NOND=true;;
     r) SHOW_ALL_PKGS=false;SHOW_UNIN_RECOM=true;;
     s) SKIP_SNAPFLAT=true;;
     u) SHOW_ALL_PKGS=false;SHOW_UNIN=true;;
     v) SHOW_ALL_PKGS=false;SHOW_VIRT=true;;
     z) FUZZY=true;;
    \?) exit_leave "[${WHITE_FG}${_SCRIPT}${RESET}]${RED_FG}->${RESET}unknown option:${WHITE_FG}${OPTARG}${RESET}";;
     :) exit_leave "${_SCRIPT}:${RED_FG}option: -${WHITE_FG}${OPTARG}${RESET} requires an argument${RESET}";;
	esac
done
shift $((${OPTIND} - 1))
#--End GetOpts--
 
#Execution
[[ ${_DEBUG} -eq 0 ]] && do_smcup

#handle exact matches/set SEARCHTERM
if [[ -n ${1} ]];then
	SEARCHTERM=${1}
	[[ ${FUZZY} == "false" ]] && ARG_PATTERN="^${1}" || ARG_PATTERN="${1}"
fi

#show all as default?
if [[ ${SHOW_ALL_PKGS} == "true" ]];then
     SHOW_INST=true
     SHOW_UNIN=true
     SHOW_CONF=true
fi

#handle architecture
[[ ${I386} == "true" ]] && ARCH_PATTERN="(?architecture(i386) | ?architecture(all))" || ARCH_PATTERN="(?architecture(amd64) | ?architecture(all))"

#set filter pattern
if [[ ${SHOW_ALL_PKGS} == "true" ]];then
	FILTER_PATTERN=''
elif [[ ${SHOW_CONF} == "true" ]];then
	FILTER_PATTERN="~c" 
elif [[ ${SHOW_INST} == "true" ]];then
	FILTER_PATTERN="~i" 
elif [[ ${SHOW_UNIN} == "true" ]];then
	FILTER_PATTERN="?not(?installed)" 
elif [[ ${SHOW_UNIN_RECOM} == "true" ]];then
	FILTER_PATTERN="~RBrecommends:~i"
elif [[ ${SHOW_VIRT} == "true" ]];then
	FILTER_PATTERN="~Rprovides:~i ~v" 
	ARCH_PATTERN=''
fi

[[ ${MATCH_DESC} == "true" ]] && ARG_PATTERN='' #SEARCHTERM handles match
PATTERN=${ARCH_PATTERN}' '${FILTER_PATTERN}' '${ARG_PATTERN}

#newly added ppa's?
DO_APT_UPDATE=false

if [[ -e ${_LAST_APT_UPD} ]];then
	MODIFIED=$(stat -c '%Y' ${_SOURCES})
	LAU=$(<${_LAST_APT_UPD})
	DIFF=$(( MODIFIED - LAU ))
	if [[ ${DIFF} -ne 0 ]];then
		DO_APT_UPDATE=true
	fi
else
	DO_APT_UPDATE=true
fi

if [[ ${DO_APT_UPDATE} == true ]];then
	msg_box "Updating sources - please wait..."
	sudo apt-get update > /dev/null 2>&1
	stat -c '%Y' ${_SOURCES} >${_LAST_APT_UPD}
fi

[[ ${_DEBUG} -gt 0 ]] && echo -n "PATTERN:${PATTERN}"

#get data
set_package_list ${PATTERN}
[[ -z ${LIST} ]] && exit_leave $(msg_warn "No ${OBJTYPE}:${SEARCHTERM} found...")

if [[ ${TO_FILE} == 'true' ]];then
	FN="${0:t}.$(date +'%s')" 
	msg_box -p -PK "Writing output to ${FN}" 
	for L in ${LIST};do
		echo ${L}
	done > ${FN}
fi

#set headings
list_set_header 'printf "%s Count:${WHITE_FG}%-d${RESET}, Filter:${WHITE_FG}%s${RESET}, Fuzzy match:${WHITE_FG}%s${RESET}, Description search:${WHITE_FG}%s${RESET}\tPage:${WHITE_FG}%-d${RESET} of ${WHITE_FG}%-d${RESET}" ${(C)OBJTYPE} ${#_LIST} "${PATTERN}" ${FUZZY} ${MATCH_DESC} ${PAGE} ${MAX_PAGES}'
list_set_header 'printf " "'
list_set_header 'printf "%6s${CYAN_FG}%-12s %-*s %-*s${RESET}" "" "State" ${LONGEST_NAME} "Name" ${LONGEST_DESC} "Description"'
list_set_header 'printf "%6s${WHITE_FG}%-12s %-*s %-*s${RESET}" "" "$(str_unicode_line 12)" ${LONGEST_NAME} "$(str_unicode_line ${LONGEST_NAME})" ${LONGEST_DESC}  "$(str_unicode_line ${LONGEST_DESC})"'

#set line item
list_set_line_item ' 
local PKG_STATE=$(get_package_state ${_LIST[${ARRAY_NDX}]});
local PKG_NAME=$(get_package_name ${_LIST[${ARRAY_NDX}]});
local PKG_DESC=$(get_package_desc ${_LIST[${ARRAY_NDX}]});
local ST_COLOR=$(set_state_color ${PKG_STATE});
printf "${BOLD}${WHITE_FG}%4s${RESET}) ${SHADE}${BAR}${ST_COLOR}%-12s${RESET}${BOLD}${SHADE}${BAR} %-*s${RESET}${SHADE}${BAR} %-.*s${RESET}\n" ${ARRAY_NDX} ${PKG_STATE} ${LONGEST_NAME} ${PKG_NAME} ${LONGEST_DESC} ${PKG_DESC}
'
list_set_action_msgs 'install-uninstall app / view app info:'  app
list_user_prompt_style msg_box
list_set_no_top_offset #place the first detail line immediately after heading
list_set_barlines true

while true;do
	#get selection
	list_select ${LIST}
	[[ ${?} -eq 0 ]] && break

	#get selections
	MARKED=($(list_get_selected))

	if [[ $(list_get_selected_count) -ne 0 ]];then
		list_set_page_hold
		for M in ${MARKED};do
			action_warn ${M}
			[[ ${?} -eq 0 ]] && action_do ${M} ${_MSG_KEY}
		done
	fi
done

exit_leave
