#!/usr/bin/zsh
REVERSE="\033[7m"
RESET="\033[m"
BOLD="\033[1m"
BLACK_FG="\033[30m"
RED_FG="\033[31m"
GREEN_FG="\033[32m"
YELLOW_FG="\033[33m"
BLUE_FG="\033[34m"
MAGENTA_FG="\033[35m"
CYAN_FG="\033[36m"
WHITE_FG="\033[37m"
STRIKE="\033[9m"
ITALIC="\033[3m"
UNDER="\033[4m"

#Declarations
typeset -Z2 CNT

#Constants
_LIB=/usr/local/lib
TODAY=$(date +'%Y-%m-%d')

#Imports
source ${_LIB}/common.zsh

#--Begin GetOpts--
RESET="\033[m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"

read -r -d '' DESC<<EOF
Detect and optionally install pending updates
\tNote: This utility only updates the current installation
\tTo upgrade to a new release run: do-release-upgrade -d
EOF

SCRIPT=${0:t}
function parse_opts {
	local OPTS=$@
	local -a OPTSTRING
	local O

	for O in {1..${#OPTS}};do
		[[ $O -eq 1 && ${OPTS[$O]} == ":" ]] && continue
		[[ $O -gt 1 && ${OPTS[$O]} == ":" ]] && OPTSTRING+="<PARAM>" && continue
		OPTSTRING+="-${OPTS[$O]}"
	done
	echo $OPTSTRING
}

function usage {
	local PENDING_MSGS=${@}
	local OPTS=$(parse_opts $OPTSTR)

	tabs 5
	[[ ${_SMCUP} == 'true' ]] && do_rmcup

	echo -e "\n${WHITE_FG}Usage${RESET}: $SCRIPT ${WHITE_FG}[${RESET} $OPTS ${WHITE_FG}]${RESET}\n"
	echo -e "${WHITE_FG}-H${RESET} help"
	echo -e "${WHITE_FG}-D${RESET} debug"
	echo -e "${WHITE_FG}-y${RESET} no prompting"
	echo -e "${WHITE_FG}\nDESC${RESET}:${DESC}\n"

	exit_leave $(msg_err ${PENDING_MSGS})
}

OPTSTR=":HDy"

PRE_APPROVED=false
INLINE=false

OPTIND=0
while getopts ${OPTSTR} OPTION;do
	case $OPTION in
     H) usage;;
     D) dbg_set_level;;
     y) PRE_APPROVED=true;;
     :) print -u2 "${_SCRIPT}: option: -${OPTARG} requires an argument"; usage;;
    \?) print -u2 "${_SCRIPT}: unknown option -${OPTARG}"; usage;;
	esac
done
shift $((OPTIND -1))
#--End GetOpts--

#--Execution--
[[ ${_DEBUG} -eq 0 ]] && do_smcup

LIST=("${(@f)$(sudo apt-get -s dist-upgrade)}")

PENDING=false
for L in ${LIST};do
	[[ ${L:l} =~ "^inst" ]] && PENDING=true
done

if [[ ${PENDING} == 'false' ]];then
	exit_leave $(msg_info "No updates available")
fi

if [[ ${PRE_APPROVED} == false ]];then
	tp cup 0 0
	echo "Finding ${WHITE_FG}obsolete packages${RESET} and any ${WHITE_FG}pending updates${RESET}...\n"
	sleep .5

	LIST=("${(@f)$(sudo apt-get -s dist-upgrade)}")

	CNT=0
	SECTION=?
	I_HEADER_OUT=false
	C_HEADER_OUT=false
	R_HEADER_OUT=false
	GETPKGLIST=false
	DOUPGRADE=false

	for L in ${LIST};do
		[[ ${L:l} =~ "^inst" ]] && SECTION=INST 
		[[ ${L:l} =~ "^remv" ]] && SECTION=REMV 

		IN_SECTION=true
		case ${SECTION} in
			INST) 
				DOUPGRADE=true
				[[ ${I_HEADER_OUT} == false ]] && echo "\n${GREEN_FG}Pending installations...${RESET}" && CNT=0
				I_HEADER_OUT=true
				;;
			REMV) 
				[[ ${R_HEADER_OUT} == false ]] && echo "\n${GREEN_FG}Pending removals...${RESET}" && CNT=0
				R_HEADER_OUT=true
				;;
			*) IN_SECTION=false;;
		esac

		(( CNT++ ))

		if [[ ${IN_SECTION} == true ]];then
			echo "${WHITE_FG}${CNT})${RESET}${L[5,-1]}"
		else
			if [[ ${GETPKGLIST} == true ]];then
				PKGLIST=(${L})
				GETPKGLIST=false
				echo "\n${GREEN_FG}Found obsolete packages${RESET}:"
				for P in ${=PKGLIST};do
					echo "-> ${P}"
				done
				continue
			fi
			if [[ ${L} =~ "no longer required:$" ]];then
				GETPKGLIST=true
				continue
			fi
			if [[ ${L} =~ "autoremove" ]];then
				echo -n "\n${RED_FG}Remove${RESET} obsolete packages${WHITE_FG}?${RESET}:"
				read -sq RESPONSE
				if [[ ${RESPONSE} != "n" ]];then
					sudo apt-get -y autoremove
				else
					echo "no\n"
				fi
				continue
			fi
			echo "${WHITE_FG}${L}${RESET}"
		fi
	done

	if [[ ${DOUPGRADE} == true && ${PRE_APPROVED} == false ]];then
		echo -n "\n${GREEN_FG}Install${RESET} updates${WHITE_FG}?${RESET}:"
		read -sq RESPONSE
		if [[ ${RESPONSE} != "n" || ${PRE_APPROVED} == true ]];then
			sudo apt-get -y dist-upgrade
		else
			echo "no\n"
		fi
	fi
fi

if [ -x /var/run/reboot-required ]; then
	exit_leave $(msg_warn "Reboot required")
fi

exit_leave
