#!/usr/bin/zsh
#Inline ansi
BOLD="\033[1m"
ITALIC="\033[3m"
RESET="\033[m"
REVERSE="\033[7m"
STRIKE="\033[9m"
UNDER="\033[4m"

BLACK_BG="\033[40m"

BLUE_FG="\033[34m"
CYAN_FG="\033[36m"
GREEN_FG="\033[32m"
MAGENTA_FG="\033[35m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"
YELLOW_FG="\033[33m"

#Constants
_LIB=/usr/local/lib
_COL_MAX=150

#Imports
source ${_LIB}/common.zsh

#Declarations
typeset -a LIST
typeset -a RAWLIST
typeset LINE_LIMIT=100

#--Begin GetOpts--
RESET="\033[m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"

parse_opts () {
	local OPTS=${@}
	local -a OPTSTRING
	local LETTER_OPT
	local O

	for O in {1..${#OPTS}};do
		[[ ${OPTS[${O}]} =~ '[a-z]' ]] && LETTER_OPT=${OPTS[${O}]}
		[[ ${O} -eq 1 && ${OPTS[${O}]} == ":" ]] && continue
		[[ ${O} -gt 1 && ${OPTS[${O}]} == ":" ]] && OPTSTRING+=$(opt_type ${LETTER_OPT}) && continue
		OPTSTRING+="-${OPTS[${O}]}"
	done
	echo ${OPTSTRING}
}

opt_type () {
	local OPT=${1}
	case ${OPT} in
		s) echo "<SEARCHTERM>";;
		m) echo "<LINES>";;
		p) echo "<PATH>";;
	esac
}

usage () {
	local OPTS=$(parse_opts ${OPTSTR})
	local -a PENDING_MSGS=(${@})

	tabs 5
	[[ ${_SMCUP} == 'true' ]] && do_rmcup

	echo -e "\n${WHITE_FG}Usage${RESET}: ${_SCRIPT} ${WHITE_FG}[${RESET}${OPTS}${WHITE_FG}]${RESET} $(opt_type s)\n"
	echo -e "${WHITE_FG}-H${RESET} help"
	echo -e "${WHITE_FG}-D${RESET} debug"
	echo -e "${WHITE_FG}-I${RESET} case sensitive"
	echo -e "${WHITE_FG}-e${RESET} exclude search"
	echo -e "${WHITE_FG}-l${RESET} list files"
	echo -e "${WHITE_FG}-L${RESET} list files on one line"
	echo -e "${WHITE_FG}-m $(opt_type m)${RESET} max lines to process"
	echo -e "${WHITE_FG}-n${RESET} line numbers"
	echo -e "${WHITE_FG}-o${RESET} only matched"
	echo -e "${WHITE_FG}-p $(opt_type p)${RESET} alternate path"
	echo -e "${WHITE_FG}-r${RESET} recurse"
	echo -e "${WHITE_FG}-w${RESET} whole word match"
	echo -e "\n${WHITE_FG}DESC${RESET}:find files containing <SEARCHTERM> in or below the current directory\n"

	exit_leave $(msg_err ${PENDING_MSGS})
}

OPTSTR=":HDIelLm:nop:rw"

CASE_OPT='-i'
CASE_SENSE=false
EXCLUDE_OPT=''
FILELIST=false
LINENUM_OPT=''
LISTFILES_OPT=''
MYPATH=${PWD}/*
ONE_LINE=false
ONLY_OPT=''
RECURSE=false
RECURSE_OPT=''
WORD_OPT=''
MAX_LINES=0

OPTIND=0
while getopts ${OPTSTR} OPTION;do
	case ${OPTION} in
     H) usage;;
	  D) dbg_set_level;;
     I) CASE_OPT='';CASE_SENSE=true;;
     e) EXCLUDE_OPT=-v;;
     l) LISTFILES_OPT=-l;FILELIST=true;;
     L) LISTFILES_OPT=-l;FILELIST=true;ONE_LINE=true;;
     m) MAX_LINES=${OPTARG};;
     n) LINENUM_OPT=-n;;
     o) ONLY_OPT=-o;;
     p) MYPATH=${OPTARG}/*;;
     r) RECURSE_OPT=-r;RECURSE=true;;
     w) WORD_OPT=-w;;
     :) print -u2 "${_SCRIPT}: option: -${OPTARG} requires an argument"; usage;;
    \?) print -u2 "${_SCRIPT}: unknown option -${OPTARG}"; usage;;
	esac
done
shift $((OPTIND -1))
#--End GetOpts--
SEARCHTERM=${@} 

#Execution
[[ ${_DEBUG} -eq 0 && FILELIST == 'false' ]] && do_smcup

[[ -z ${SEARCHTERM} ]] && usage "Missing argument: <SEARCHTERM>"
[[ ! -t 0 ]] && exit_leave $(msg_warn "Unable to accept piped input")

CMD=$(echo "grep -R -P -I -d skip --color=never ${RECURSE_OPT} ${LINENUM_OPT} ${EXCLUDE_OPT} ${ONLY_OPT} ${WORD_OPT} ${CASE_OPT} '"${SEARCHTERM}"' ${MYPATH} 2>/dev/null | grep --color=always '"${SEARCHTERM}"' ")
RAWLIST=("${(f)$(eval ${CMD})}")

LONGEST_FN=0
LONGEST_LN=0
NDX=0
for L in ${RAWLIST};do
	((NDX++))
	[[ ${MAX_LINES} -ne 0 && ${NDX} -gt ${MAX_LINES} ]] && break
	if [[ ${FILELIST} == 'false' ]];then
		clear
		tput cup 0 0; tput el; printf "\rProcessing line ${WHITE_FG}%d${RESET} of ${WHITE_FG}%d${RESET} lines ${WHITE_FG}%%${BOLD}${GREEN_FG}%.2f${RESET}" ${NDX} ${#RAWLIST} $(( NDX * 100. / ${#RAWLIST} ))
	fi
	FN=$(cut -d: -f1 <<<${L})
	LN=$(cut -d: -f2- <<<${L})
	LN=${LN[1,${_COL_MAX}]} #limit usable line length; some files have no line breaks
	LN=$(tr -d '\012\015' <<<${LN})
	LN=$(tr -s '[:space:]' <<<${LN})
	LN=$(sed 's/[\t\n]/ /' <<<${LN})
	LN=$(sed 's/\x2a//g' <<<${LN})
	LN=$(str_trim <<<${LN})
	[[ ! $(file -L ${FN}) =~ 'text' ]] && continue
	if [[ ${FN:h} != ${PWD} ]];then
		FNP=$(pathabv -l15 <<<${FN})
	else
		FNP=${FN:t}
	fi
	[[ ${#FNP} -gt ${LONGEST_FN} ]] && LONGEST_FN=${#FNP}
	[[ ${#LN} -gt ${LONGEST_LN} ]] && LONGEST_LN=${#LN}
	LIST+="${FNP}|${LN}"
done
echo "\n" >&2

if ! arr_is_populated "${LIST}";then
	exit_leave $(msg_warn "No file(s) found containing:${SEARCHTERM}\\\nCMD:${CMD}")
fi

if [[ ${FILELIST} == 'true' ]];then
	UNIQ=("${(f)$(
	for L in ${LIST};do
		FN=$(cut -d'|' -f1 <<<${L})
		echo ${FN}
	done | sort -u
	)}")
	for L in ${UNIQ};do
		[[ -h ${L} ]] && continue
		[[ ${ONE_LINE} == 'true' ]] && echo -n "${L} " || echo ${L}
	done
else
	{
	if [[ ${FILELIST} == 'false' ]];then
		tput cup 1 0; echo ${CMD} | tr -s '[:space:]'
		[[ ${RECURSE} == 'true' ]] && RECURSE_MSG=" (recursive)" || RECURSE_MSG=''
		[[ ${CASE_SENSE} == 'true' ]] && CASE_MSG=" (case sensitive)" || CASE_MSG=''
		[[ ${MAX_LINES} -ne 0 ]] && ROW_MSG=" (limit ${MAX_LINES})" || ROW_MSG=''
		echo "Path:${WHITE_FG}${MYPATH}${RECURSE_MSG}${RESET}, Search:${WHITE_FG}${SEARCHTERM}${CASE_MSG}${RESET}, Result: ${WHITE_FG}${#RAWLIST}${ROW_MSG}${RESET} lines\n\n"
		if [[ -n ${LINENUM_OPT} ]];then
			[[ ${LONGEST_LN} -gt $(( _COL_MAX - LONGEST_FN )) ]] && LONGEST_LN=$(( (_COL_MAX - LONGEST_FN) - 7 ))
			REM=$(( (_COL_MAX - LONGEST_FN) - 8))
			printf "${WHITE_FG}%-*s %5s %-*s${RESET}\n" ${LONGEST_FN} "File" "Line" ${LONGEST_LN} "Text"
			echo -n "${MAGENTA_FG}$(str_unicode_line $((LONGEST_FN--)))  ${MAGENTA_FG}$(str_unicode_line 4)${RESET} ${MAGENTA_FG}$(str_unicode_line $((LONGEST_LN - 4)))${RESET}"
			echo
		else
			[[ ${LONGEST_LN} -gt $(( _COL_MAX - LONGEST_FN )) ]] && LONGEST_LN=$(( (_COL_MAX - LONGEST_FN) - 4 ))
			REM=$(( (_COL_MAX - LONGEST_FN) - 4))
			printf "${WHITE_FG}%-*s %-*s${RESET}\n" ${LONGEST_FN} "File" ${LONGEST_LN} "Text"
			echo -n "${MAGENTA_FG}$(str_unicode_line $((LONGEST_FN--))) ${MAGENTA_FG}$(str_unicode_line $((LONGEST_LN--)))${RESET}"
			echo
		fi
	fi

	NDX=0
	for L in ${LIST};do
		((NDX++))
		[[ $(( NDX % 2 )) -ne 0 ]] && BAR=${BLACK_BG} || BAR=''
		FN=$(cut -d'|' -f1 <<<${L})
		LN=$(cut -d'|' -f2- <<<${L})
		if [[ -n ${LINENUM_OPT} ]];then
			LNUM=$(cut -d: -f1 <<<${LN})
			LN=$(cut -d: -f2- <<<${LN})
			LN=$(tr -d '\012\015' <<<${LN})
			LN=$(tr -s '[:space:]' <<<${LN})
			LN=$(sed 's/[\t\n]/ /' <<<${LN})
			LN=$(sed 's/\x2a//g' <<<${LN})
			LN=$(str_trim <<<${LN})
			printf "${BAR}${WHITE_FG}%-*s ${CYAN_FG}%5s ${RESET}%-*.${REM}s\n" ${LONGEST_FN} ${FN} ${LNUM} ${LONGEST_LN} ${LN}
		else
			printf "${BAR}${WHITE_FG}%-*s ${RESET}%-*.${REM}s\n" ${LONGEST_FN} ${FN} ${LONGEST_LN} ${LN}
		fi
	done
	} | mypager
	[[ ${?} -ne 0 ]] && echo -n "${RESET}Press any key..." && read
fi

exit_leave

