#!/usr/bin/zsh
#Inline ansi
BOLD="\033[1m"
ITALIC="\033[3m"
RESET="\033[m"
REVERSE="\033[7m"
STRIKE="\033[9m"
UNDER="\033[4m"

BLUE_FG="\033[34m"
CYAN_FG="\033[36m"
GREEN_FG="\033[32m"
MAGENTA_FG="\033[35m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"
YELLOW_FG="\033[33m"

BLACK_BG="\033[40m"
BLUE_BG="\033[44m"
CYAN_BG="\033[46m"
GREEN_BG="\033[42m"
MAGENTA_BG="\033[45m"
RED_BG="\033[41m"
WHITE_BG="\033[47m"
YELLOW_BG="\033[43m"

#Echoed ansi
E_BOLD=$(echo -n "\033[1m")
E_ITALIC=$(echo -n "\033[3m")
E_RESET=$(echo -n "\033[m")
E_REVERSE=$(echo -n "\033[7m")
E_STRIKE=$(echo -n "\033[9m")
E_UNDER=$(echo -n "\033[4m")

E_BLUE_FG=$(echo -n "\033[34m")
E_CYAN_FG=$(echo -n "\033[36m")
E_GREEN_FG=$(echo -n "\033[32m")
E_MAGENTA_FG=$(echo -n "\033[35m")
E_RED_FG=$(echo -n "\033[31m")
E_WHITE_FG=$(echo -n "\033[37m")
E_YELLOW_FG=$(echo -n "\033[33m")

E_BLACK_BG=$(echo -n "\033[40m")
E_BLUE_BG=$(echo -n "\033[44m")
E_CYAN_BG=$(echo -n "\033[46m")
E_GREEN_BG=$(echo -n "\033[42m")
E_MAGENTA_BG=$(echo -n "\033[45m")
E_RED_BG=$(echo -n "\033[41m")
E_WHITE_BG=$(echo -n "\033[47m")
E_YELLOW_BG=$(echo -n "\033[43m")

#Constants
_LIB=/usr/local/lib
_ALIAS_FN=/etc/zsh/aliases

#Imports
zmodload zsh/pcre
source ${_LIB}/common.zsh

#Declarations
typeset -A ALIAS_LIST

#Functions
function strip {
	local LINE=${1}

	LINE=$(echo ${LINE} | sed "s/[\'\"]//g") 
	echo ${LINE}
}

do_header () {
	local MSGS=${@}

	echo -n "Aliases defined in:${WHITE_FG}${_ALIAS_FN}${RESET}"
	[[ -n ${MSGS} ]] && echo " (${MSGS})" || echo
	printf "${CYAN_FG}%12s${RESET}    ${GREEN_FG}%-50s${RESET}\n"  "Alias" "Command"
	printf "${CYAN_FG}%12s${RESET}    ${GREEN_FG}%-50s${RESET}\n"  $(str_unicode_line 5) $(str_unicode_line 7)
}

do_match () {
	local WORD=$1
	local STR=$2
	local REGEX=$3
	local OPTS
	local RC

	[[ ${WORD} == "true" ]] && OPTS="w" || OPTS=""
	[[ ${CASE} == "true" ]] && OPTS+="qP" || OPTS+="qiP"

	grep -${OPTS} "${REGEX}" <<<${STR}
	RC=$?

	[[ ${_DEBUG} -gt 0 ]] && dbg "STRING:${STR} | grep OPTS: -${OPTS} REGEX: ${REGEX} RC:$RC"

	echo $RC
}

#--Begin GetOpts--
RESET="\033[m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"

read -r -d '' DESC<<EOF
Search/View aliases
\tPass <SEARCHTERM> to limit criteria
\tSearch is case insensitive by default
EOF

parse_opts () {
	local OPTS=${@}
	local -a OPTSTRING
	local LETTER_OPT
	local O

	for O in {1..${#OPTS}};do
		[[ ${OPTS[${O}]} =~ '[a-z]' ]] && LETTER_OPT=${OPTS[${O}]}
		[[ ${O} -eq 1 && ${OPTS[${O}]} == ":" ]] && continue
		[[ ${O} -gt 1 && ${OPTS[${O}]} == ":" ]] && OPTSTRING+=$(opt_type ${LETTER_OPT}) && continue
		OPTSTRING+="-${OPTS[${O}]}"
	done
	echo ${OPTSTRING}
}

opt_exists () {
	local OPT=${1}
	[[ $(( $OPTIONS[(Ie)${OPT}] )) -ne 0 ]] && return 0 || return 1
}

opt_type () {
	local OPT=${1}
	case ${OPT} in
		d) echo "<DIR>";;
		f) echo "<FILE>";;
		s) echo "<SEARCHTERM>";;
		t) echo "<FILE_TYPE>";;
	esac
}

usage () {
	local OPTS=$(parse_opts ${OPTSTR})
	local -a PENDING_MSGS=(${@})

	tabs 5
	[[ ${_SMCUP} == 'true' ]] && do_rmcup

	echo -e "${WHITE_FG}Usage${RESET}: ${SCRIPT} ${WHITE_FG}[${RESET}${OPTS}${WHITE_FG}]${RESET} [$(opt_type s)]\n"
	echo -e "${WHITE_FG}-H${RESET} help"
	echo -e "${WHITE_FG}-D${RESET} debug"
	echo -e "${WHITE_FG}-a${RESET} match alias only"
	echo -e "${WHITE_FG}-c${RESET} match command only"
	echo -e "${WHITE_FG}-e${RESET} output only command"
	echo -e "${WHITE_FG}-I${RESET} case sensitive"
	echo -e "${WHITE_FG}-x${RESET} exact match"
	echo -e "${WHITE_FG}\nDESC${RESET}:${DESC}"

	exit_leave $(msg_err ${PENDING_MSGS})
}

typeset -a OPTIONS
OPTSTR=":HDaceIx"
OPTIND=0

EXACT=false
MATCH_BOTH=true
MATCH_ALIAS_ONLY=false
MATCH_CMD_ONLY=false
OUTPUT_CMD_ONLY=false
CASE=false
OPT_Y=?

while getopts ${OPTSTR} OPTION;do
	case $OPTION in
     H) usage;;
     D) dbg_set_level;;
     I) CASE=true;;
     a) MATCH_BOTH=false;MATCH_ALIAS_ONLY=true;MATCH_CMD_ONLY=false;;
     c) MATCH_BOTH=false;MATCH_CMD_ONLY=true;;
     e) OUTPUT_CMD_ONLY=true;;
     x) EXACT=true;;
     :) print -u2 "${RED_FG}${SCRIPT}${RESET}: option: -${OPTARG} requires an argument"; usage;;
    \?) print -u2 "${RED_FG}${SCRIPT}${RESET}: unknown option -${OPTARG}"; usage;;
	esac
	[[ ${OPTION} != 'D' ]] && OPTIONS+=${OPTION}
done
shift $((OPTIND -1))
#--End GetOpts--

#---Execution---
[[ ${_DEBUG} -gt 0 ]] && dbg "EXACT=${EXACT} OUTPUT_CMD_ONLY=${OUTPUT_CMD_ONLY} MATCH_BOTH=${MATCH_BOTH}"

#Build list
ALIASES=("${(@f)$(cat ${_ALIAS_FN} | grep ^alias | sort)}")
for A in ${ALIASES};do
	ALIAS=$(echo ${A} | cut -d= -f1 | sed -e 's/^alias//g' -e 's/.*-g//g')
	DEF=$(echo ${A} | cut -d= -f2-)
	ALIAS_LIST[${ALIAS}]=${DEF}
	[[ ${_DEBUG} -gt 1 ]] && dbg "ALIASES:${#ALIASES} -> ALIAS:${ALIAS} DEF:${DEF}"
done

#Apply search criteria
LIST_ALL=true
INFO_TEXT="all aliases"
if [[ $# -ge 1 ]];then
	SEARCH_PARAM=${1}
	[[ ${EXACT} == true ]] && INFO_TEXT="exact matches only" || INFO_TEXT="partial matches allowed"
	LIST_ALL=false
fi

if [[ ${MATCH_BOTH} == "true" ]];then
	FILTER="- matching aliases OR commands"
elif [[ ${MATCH_ALIAS_ONLY} == "true" ]];then
	FILTER="- matching aliases ONLY"
elif [[ ${MATCH_CMD_ONLY} == "true" ]];then
	FILTER="- matching commands ONLY"
fi

HDR=true
if [[ ${OUTPUT_CMD_ONLY} == "true" ]];then
	FILTER="${FILTER}- output is command only"
	HDR=false
fi

#Process list
{
SEARCH_PARAM=${SEARCH_PARAM}
[[ ${_DEBUG} -gt 0 ]] && dbg "SEARCH_PARAM:${SEARCH_PARAM}"

REGEX="${SEARCH_PARAM}"
[[ ${EXACT} == "true" ]] && IS_WORD=true || IS_WORD=false

HEADER_OUT=false
HIT=false
durable_set HITS HIT false
for A in ${(ko)ALIAS_LIST};do
	[[ ${_DEBUG} -gt 0 ]] && dbg "ASSOC KEY:${A} VALUE:${GREEN_FG}$(strip ${ALIAS_LIST[${A}]})${RESET}"
	if [[ ${LIST_ALL} == "true" ]];then
		[[ ${HDR} == "true" ]] && do_header "${INFO_TEXT} ${FILTER}" && HDR=false
		printf "${WHITE_FG}%12s${RESET} %-50s\n" ${A} "$(strip ${ALIAS_LIST[${A}]})"
		continue
	fi
	LAST_ALIAS=?
	if [[ (${MATCH_ALIAS_ONLY} == "true" || ${MATCH_BOTH} == "true" ) ]];then
		LEFT_SIDE=$(echo ${A} | sed -e 's/^[ \t]*//' | sed -e 's/[ \t]*$//')
		if [[ $(do_match ${IS_WORD} ${LEFT_SIDE} ${REGEX}) -eq 0 ]];then
			HIT=true
			durable_set HITS HIT true
			[[ ${_DEBUG} -gt 0 ]] && dbg "${BOLD}${GREEN_FG}MATCH${RESET}"
			if [[ ${OUTPUT_CMD_ONLY} == "true" ]];then
				echo $(strip ${ALIAS_LIST[${A}]})
			else
				if [[ ${HEADER_OUT} == 'false' ]];then
					do_header "${INFO_TEXT} ${FILTER}"
					HEADER_OUT=true
				fi
				printf "${CYAN_FG}%12s${RESET} -> ${WHITE_FG}%-50s${RESET}\n" ${A} "$(strip ${ALIAS_LIST[${A}]})"
				LAST_ALIAS=${A}
			fi
		else
			[[ ${_DEBUG} -gt 0 ]] && dbg "${RED_FG}NO MATCH${RESET}"
		fi
	fi
	if [[ (${MATCH_CMD_ONLY} == "true"  || ${MATCH_BOTH} == "true" ) ]];then
		LEFT_SIDE=$(echo ${ALIAS_LIST[${A}]} | sed -e 's/^[ \t]*//' | sed -e 's/[ \t]*$//')
		if [[ $(do_match ${IS_WORD} ${LEFT_SIDE} ${REGEX}) -eq 0 ]];then
			HIT=true
			durable_set HITS HIT true
			[[ ${_DEBUG} -gt 0 ]] && dbg "${BOLD}${GREEN_FG}MATCH${RESET}"
			if [[ ${OUTPUT_CMD_ONLY} == "true" ]];then
				echo $(strip ${ALIAS_LIST[${A}]})
			else
				if [[ ${HEADER_OUT} == 'false' ]];then
					do_header "${INFO_TEXT} ${FILTER}"
					HEADER_OUT=true
				fi
				[[ ${A} == ${LAST_ALIAS} ]] && continue #Avoid duplicate output
				printf "${CYAN_FG}%12s${RESET} -> ${WHITE_FG}%-50s${RESET}\n" ${A} "$(strip ${ALIAS_LIST[${A}]})"
			fi
		else
			[[ ${_DEBUG} -gt 0 ]] && dbg "${RED_FG}NO MATCH${RESET}"
		fi
	fi
done

if [[ ${HIT} == 'false' ]];then
	if [[ ${MATCH_ALIAS_ONLY} == "true" ]];then
		echo "${RED_FG}No matches${RESET} for ${ITALIC}alias${RESET}:${WHITE_FG}${SEARCH_PARAM}${RESET}"
	elif [[ ${MATCH_CMD_ONLY} == "true" ]];then
		echo "${RED_FG}No matches${RESET} for ${ITALIC}command${RESET}:${WHITE_FG}${SEARCH_PARAM}${RESET}"
	else
		echo "${RED_FG}No matches${RESET} for:${WHITE_FG}${SEARCH_PARAM}${RESET}"
	fi
fi
} | mypager

[[ $(durable_get HITS HIT) == 'false' ]] && set_exit_value 1

exit_leave
