#!/usr/bin/zsh
#Inline ansi
BOLD="\033[1m"
ITALIC="\033[3m"
RESET="\033[m"
REVERSE="\033[7m"
STRIKE="\033[9m"
UNDER="\033[4m"

BLUE_FG="\033[34m"
CYAN_FG="\033[36m"
GREEN_FG="\033[32m"
MAGENTA_FG="\033[35m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"
YELLOW_FG="\033[33m"

#Declarations
typeset -a LIST
typeset -R2 SNDX=0
typeset -a SUBLIST

#Constants
_LIB=/usr/local/lib

#Globals
g_LIMIT=200

#Imports
source ${_LIB}/common.zsh

#Functions
is_valid_int () {
	local ARG=${1}
	local REGEX='^[0-9]+$'

	[[ ${ARG} =~ ${REGEX} ]] && return 0
	return 1
}

#--Begin GetOpts--
RESET="\033[m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"

read -r -d '' DESC<<EOF
Search and display system icons
EOF

parse_opts () {
	local OPTS=${@}
	local -a OPTSTRING
	local LETTER_OPT
	local O

	for O in {1..${#OPTS}};do
		[[ ${OPTS[${O}]} =~ '[a-z]' ]] && LETTER_OPT=${OPTS[${O}]}
		[[ ${O} -eq 1 && ${OPTS[${O}]} == ":" ]] && continue
		[[ ${O} -gt 1 && ${OPTS[${O}]} == ":" ]] && OPTSTRING+=$(opt_type ${LETTER_OPT}) && continue
		OPTSTRING+="-${OPTS[${O}]}"
	done
	echo ${OPTSTRING}
}

opt_exists () {
	local OPT=${1}
	[[ $(( $OPTIONS[(Ie)${OPT}] )) -ne 0 ]] && return 0 || return 1
}

opt_type () {
	local OPT=${1}
	case ${OPT} in
		d) echo "<DIR>";;
		f) echo "<FILE>";;
		l) echo "<INTEGER>";;
		t) echo "<FILE_TYPE>";;
	esac
}

usage () {
	local OPTS=$(parse_opts ${OPTSTR})
	local -a PENDING_MSGS=(${@})

	tabs 5
	[[ ${_SMCUP} == 'true' ]] && do_rmcup

	echo -e "\n${WHITE_FG}Usage${RESET}: ${_SCRIPT} ${WHITE_FG}[${RESET}${OPTS}${WHITE_FG}]${RESET} [<SEARCHTERM>]\n"
	echo -e "${WHITE_FG}-H${RESET} help"
	echo -e "${WHITE_FG}-D${RESET} debug"
	echo -e "${WHITE_FG}-l $(opt_type l)${RESET} set limit on icons per page (default:${g_LIMIT})"
	echo -e "${WHITE_FG}-s${RESET} limit selection by icons size"
	echo -e "\n${WHITE_FG}DESC${RESET}:${DESC}"

	exit_leave $(msg_err ${PENDING_MSGS})
}

typeset -a OPTIONS
OPTSTR=":HDl:s"
OPTIND=0

GET_SIZE=false

while getopts ${OPTSTR} OPTION;do
	case $OPTION in
     H) usage;;
     D) dbg_set_level;;
	  l) if is_valid_int ${OPTARG};then
           g_LIMIT=${OPTARG}
        else
			  exit_leave $(msg_warn "Invalid integer")
        fi;;
     s) GET_SIZE=true;;
     :) print -u2 "${RED_FG}${_SCRIPT}${RESET}: option: -${OPTARG} requires an argument"; usage;;
    \?) print -u2 "${RED_FG}${_SCRIPT}${RESET}: unknown option -${OPTARG}"; usage;;
	esac
	[[ ${OPTION} != 'D' ]] && OPTIONS+=${OPTION}
done
shift $((OPTIND -1))
#--End GetOpts--

#Execution
[[ ${_DEBUG} -eq 0 ]] && do_smcup
[[ ${#} -ne 0 ]] && SEARCHTERM=${1}

SIZE=''
if [[ ${GET_SIZE} == 'true' ]];then
	SIZES=("${(f)$(find /usr/share/icons -type d -regex ".*[0-9]x[0-9].*" | grep -oE '[0-9]?[0-9]?[0-9]x[0-9][0-9]?[0-9]?' | sort -nu)}")

	selection_list_set ${SIZES}
	selection_list -x11 -y32 "<w>Select icon size<N>"
	[[ ${_SELECTION_VALUE} == '?' ]] && echo "${BOLD}${RED_FG}Cancelled...${RESET}" && exit_leave
	SIZE=${_SELECTION_VALUE}
fi

if [[ -n ${SIZE} ]];then
	DIRLIST=("${(f)$(find /usr/share/icons -type d  ! -path /usr/share/icons | grep "${SIZE}")}")
else
	DIRLIST=("${(f)$(find /usr/share/icons -type d ! -path /usr/share/icons)}")
fi

typeset -a RAWLIST
NDX=0
for D in ${DIRLIST};do
	((NDX++))
	RAWLIST+=("${(f)$(find ${D} -maxdepth 1 -type f -name "*${SEARCHTERM}*png")}")
	tput cup 0 0; printf "\rProcessing directory ${WHITE_FG}%d${RESET} of ${WHITE_FG}%d${RESET} directories ${WHITE_FG}%%${BOLD}${GREEN_FG}%.2f${RESET}" ${NDX} ${#DIRLIST} $(( NDX * 100. / ${#DIRLIST} )) 
	if [[ -n $(tr -d '[:space:]' <<<${RAWLIST}) ]];then
		LIST+=(${RAWLIST})
		RAWLIST=()
	fi
done
echo

MSG="Found:${WHITE_FG}${#LIST}${RESET} icon file(s)"
[[ -n ${SIZE} ]] && MSG+=" of size:${WHITE_FG}${SIZE}${RESET}"
[[ -n ${SEARCHTERM} ]] && MSG+=" matching SEARCH:${WHITE_FG}${SEARCHTERM}${RESET}"

if [[ -z $(tr -d '[:space:]' <<<${LIST}) ]];then
	exit_leave $(msg_warn "No icons found...${MSG:l}")
else
	echo ${MSG}
fi

echo -n "Continue (y/n)?"
read -sq RESPONSE
[[ ${RESPONSE} == 'n' ]] && echo "\n${BOLD}${RED_FG}Cancelled...${RESET}" && exit_leave
echo

SHOWN=0
NDX=0

for L in ${LIST};do
	((NDX++))
	SUBLIST+=${L}
	if [[ ${#LIST} -gt ${g_LIMIT} && $(( NDX % g_LIMIT )) -eq 0 ]];then
		eog ${SUBLIST}
		SUBLIST=()
		SHOWN=$(( SHOWN + g_LIMIT ))
		echo -n "Continue viewing icons (y/n)?"
		read -sq RESPONSE
		[[ ${RESPONSE} == 'n' ]] && break
		echo
	fi
	if [[ $(( ${#LIST} - SHOWN )) -le ${g_LIMIT} ]];then
		eog ${LIST[$(( SHOWN+1 )),-1]}
		break
	fi
done
exit_leave
