#!/usr/bin/zsh
BOLD="\033[1m"
ITALIC="\033[3m"
RESET="\033[m"
REVERSE="\033[7m"
STRIKE="\033[9m"
UNDER="\033[4m"

BLACK_BG="\033[40m"
BLACK_FG="\033[30m"

BLUE_FG="\033[34m"
CYAN_FG="\033[36m"
GREEN_FG="\033[32m"
MAGENTA_FG="\033[35m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"
YELLOW_FG="\033[33m"
RESET="\033[m"
RED_FG="\033[31m"
GREEN_FG="\033[32m"
YELLOW_FG="\033[33m"
BLUE_FG="\033[34m"
MAGENTA_FG="\033[35m"
CYAN_FG="\033[36m"
WHITE_FG="\033[37m"
BOLD="\033[1m"

#Declarations
typeset -A _TYPE_LABELS
typeset -a RAWLIST
typeset -a LIST
typeset -a MARKED

#Constants
_LIB=/usr/local/lib
_TYPE_LABELS=(a "Last Access" m "Last Modification" c "Last Change")

#Globals
g_TAG_FILENAME=''

#Imports
source ${_LIB}/common.zsh

#Functions
action_do () {
	local M

	msg_box -p -PK "No action implemented"

	for M in ${MARKED};do
		MARKED[${M}]=0
		list_set_selected ${M} ${_GHOST_ROW}
	done
}

action_warn () {
	return 0
}

get_stat () {
	local NDX=${1}
	local TYPE=${2}
	local STAT

	case ${TYPE} in
		c) STAT=$(echo "${_LIST[${NDX}]}" | cut -d'|' -f2);;
		a) STAT=$(echo "${_LIST[${NDX}]}" | cut -d'|' -f3);;
		m) STAT=$(echo "${_LIST[${NDX}]}" | cut -d'|' -f4);;
	esac

	echo ${STAT}
}

item_decorate () {
	local NDX=${1}
	local FN=$(cut -d'|' -f1 <<<"${_LIST[${NDX}]:t}")

	[[ -d ${FN} ]] && g_TAG_FILENAME=' (d)' || g_TAG_FILENAME=''
	echo -n ${FN}${g_TAG_FILENAME}
}


#--Begin GetOpts--
RESET="\033[m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"

read -r -d '' DESC<<EOF
Show file statistics

${WHITE_FG}Access Time${RESET}: is the time when the file was last accessed or read. 
For example, using the cat, head or an editor. But remember you did not modify the contents.

${WHITE_FG}Modification Time${RESET}: is the time when the contents of the file was last modified. 
For example, you used an editor to add new content or delete some existing content.

${WHITE_FG}Change Time${RESET}: is the time when the file’s inode has been changed. 
For example, by changing permissions, ownership, file name, number of hard links.

Column sorting alternates between forward and reverse.
EOF

parse_opts () {
	local OPTS=${@}
	local -a OPTSTRING
	local LETTER_OPT
	local O

	for O in {1..${#OPTS}};do
		[[ ${OPTS[${O}]} =~ '[a-z]' ]] && LETTER_OPT=${OPTS[${O}]}
		[[ ${O} -eq 1 && ${OPTS[${O}]} == ":" ]] && continue
		[[ ${O} -gt 1 && ${OPTS[${O}]} == ":" ]] && OPTSTRING+=$(opt_type ${LETTER_OPT}) && continue
		OPTSTRING+="-${OPTS[${O}]}"
	done
	echo ${OPTSTRING}
}

opt_exists () {
	local OPT=${1}
	[[ $(( $OPTIONS[(Ie)${OPT}] )) -ne 0 ]] && return 0 || return 1
}

opt_type () {
	local OPT=${1}
	case ${OPT} in
		d) echo "<DIR>";;
		f) echo "<FILE>";;
		t) echo "<FILE_TYPE>";;
	esac
}

usage () {
	local OPTS=$(parse_opts ${OPTSTR})
	local -a PENDING_MSGS=(${@})

	tabs 5
	[[ ${_SMCUP} == 'true' ]] && do_rmcup

	echo -e "${WHITE_FG}Usage${RESET}: ${_SCRIPT} ${WHITE_FG}[${RESET} $OPTS ${WHITE_FG}]${RESET} [$(opt_type d)]\n"
	echo -e "${WHITE_FG}-H${RESET} help"
	echo -e "${WHITE_FG}-D${RESET} debug"
	echo -e "${WHITE_FG}\nDESC${RESET}:${DESC}"

	exit_leave ${PENDING_MSGS}
}

typeset -a OPTIONS
OPTSTR=":HD"
OPTIND=0

while getopts ${OPTSTR} OPTION;do
	case $OPTION in
     H) usage;;
     D) dbg_set_level;;
     :) print -u2 "${RED_FG}${_SCRIPT}${RESET}: option: -${OPTARG} requires an argument"; usage;;
    \?) print -u2 "${RED_FG}${_SCRIPT}${RESET}: unknown option -${OPTARG}"; usage;;
	esac
	[[ ${OPTION} != 'D' ]] && OPTIONS+=${OPTION}
done
shift $((OPTIND -1))
#--End GetOpts--

#Execution
[[ ${_DEBUG} -eq 0 ]] && do_smcup
[[ ${#} -ne 0 && ! -e ${1} ]] && exit_leave $(msg_warn "No files found matching:${1}")

RAWPATH=$(path_get_raw)
FPATH=$(cut -d'|' -f1 <<<${RAWPATH})
FGLOB=$(cut -d'|' -f2 <<<${RAWPATH})
PATHLBL=$(path_get_label 40)

RAWLIST=("${(f)$(eval "find ${FPATH:q} -maxdepth 1 ${FGLOB} ! -path ${FPATH:q}")}")
[[ ${_DEBUG} -gt 0 ]] && dbg "find ${FPATH} -maxdepth 1 ${FGLOB} ! -path ${FPATH:q}"

if ! arr_is_populated "${RAWLIST}";then
	exit_leave $(msg_warn "Nothing found for: ${FPATH}")
fi

LONGEST=0
NDX=0
typeset -a STATS
for L in ${(o)RAWLIST};do
		((NDX++))
		[[ ${#L:t} -ge ${LONGEST} ]] && LONGEST=${#L:t}
		tput cup 0 0; printf "\rProcessing line ${WHITE_FG}%d${RESET} of ${WHITE_FG}%d${RESET} lines ${WHITE_FG}%%${BOLD}${GREEN_FG}%.2f${RESET}" ${NDX} ${#RAWLIST} $(( NDX * 100. / ${#RAWLIST} ))
		STATS=("${(f)$(stat ${L} -c'%x %y %z' | perl -ne 'for (m/\d{4}-\d{2}-\d{2} \d{2}:\d{2}/g) { print "$_\n" }')}")
		LIST+="${(f)L}|${STATS[1]}|${STATS[2]}|${STATS[3]}" #columns are sortable; ensure printing/cutting is in the same order
done

if [[ ${_DEBUG} -gt 1 ]];then
	dbg "$(for L in ${LIST};do echo "${L}";done)"
fi

#set headings
LBL_WIDTH=17
list_set_header 'printf "Found:${WHITE_FG}%-d${RESET} $(str_pluralize file)  Path:${WHITE_FG}%-40s${RESET} %4s Page:${WHITE_FG}%-d${RESET} of ${WHITE_FG}%-d${RESET}" ${#_LIST} "${PATHLBL}" "" ${PAGE} ${MAX_PAGES}'
list_set_header 'printf " "'
list_set_header 'printf "%-*s %${LBL_WIDTH}s %${LBL_WIDTH}s %${LBL_WIDTH}s" $((LONGEST+5)) "" ${_TYPE_LABELS[c]} ${_TYPE_LABELS[a]} ${_TYPE_LABELS[m]}'
list_set_header 'printf "%-*s ${MAGENTA_FG}%${LBL_WIDTH}s %${LBL_WIDTH}s %${LBL_WIDTH}s${RESET}" $((LONGEST+5)) "" "$(str_unicode_line ${LBL_WIDTH})" "$(str_unicode_line ${LBL_WIDTH})" "$(str_unicode_line ${LBL_WIDTH})"'

#set line item
list_set_line_item ' 
[[ -d $(cut -d"|" -f1 <<<${_LIST[${ARRAY_NDX}]}) ]] && local LC=${ITALIC}${CYAN_FG} || local LC=${RESET}
printf "${BOLD}${WHITE_FG}%4s${RESET}) ${BAR}${LC}%-*s${RESET}%${LBL_WIDTH}s %${LBL_WIDTH}s %${LBL_WIDTH}s\n" ${ARRAY_NDX} ${LONGEST} "$(item_decorate ${ARRAY_NDX})" "$(get_stat ${ARRAY_NDX} c)" "$(get_stat ${ARRAY_NDX} a)" "$(get_stat ${ARRAY_NDX} m)"
'
list_set_key_msg '
printf "Press ${WHITE_FG}Home End PgUp PgDn, ${RESET}<${WHITE_FG}n${RESET}>ext, <${WHITE_FG}p${RESET}>rev, <${WHITE_FG}b${RESET}>ottom, <${WHITE_FG}t${RESET}>op, <${WHITE_FG}s${RESET}>ort columns, <${GREEN_FG}Enter${RESET}>${RESET} or <${WHITE_FG}q${RESET}>uit${RESET}"
'
list_set_prompt " "
list_set_action_msgs delete file
list_set_barlines true
list_set_sortable true
list_set_selectable false

while true;do
	list_select ${LIST}
	[[ ${?} -eq 0 ]] && break

#	#get selections (selections not implemented)
#	MARKED=($(list_get_selected))
#	
#	if [[ $(list_get_selected_count) -ne 0 ]];then
#		action_do
#	fi
done

exit_leave
