#!/usr/bin/zsh
RESET="\033[m"
RED_FG="\033[31m"
GREEN_FG="\033[32m"
YELLOW_FG="\033[33m"
BLUE_FG="\033[34m"
MAGENTA_FG="\033[35m"
CYAN_FG="\033[36m"
WHITE_FG="\033[37m"

#Constants
_LIB=/usr/local/lib
OFFICE=/usr/local/bin/libreoffice7.3

#Imports
source ${_LIB}/common.zsh

#--Begin GetOpts--
RESET="\033[m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"

read -r -d '' DESC<<EOF
Launch libreoffice for <FILE>
\tExpected extensions: odg ods xls odt doc txt
EOF

parse_opts () {
	local OPTS=${@}
	local -a OPTSTRING
	local LETTER_OPT
	local O

	for O in {1..${#OPTS}};do
		[[ ${OPTS[${O}]} =~ '[a-z]' ]] && LETTER_OPT=${OPTS[${O}]}
		[[ ${O} -eq 1 && ${OPTS[${O}]} == ":" ]] && continue
		[[ ${O} -gt 1 && ${OPTS[${O}]} == ":" ]] && OPTSTRING+=$(opt_type ${LETTER_OPT}) && continue
		OPTSTRING+="-${OPTS[${O}]}"
	done
	echo ${OPTSTRING}
}

opt_exists () {
	local OPT=${1}
	[[ $(( $OPTIONS[(Ie)${OPT}] )) -ne 0 ]] && return 0 || return 1
}

opt_type () {
	local OPT=${1}
	case ${OPT} in
		d) echo "<DIR>";;
		f) echo "<FILE>";;
		t) echo "<FILE_TYPE>";;
	esac
}

usage () {
	local OPTS=$(parse_opts ${OPTSTR})
	local -a PENDING_MSGS=(${@})

	tabs 5
	[[ ${_SMCUP} == 'true' ]] && do_rmcup

	echo -e "${WHITE_FG}Usage${RESET}: ${_SCRIPT} ${WHITE_FG}[${RESET}${OPTS}${WHITE_FG}]${RESET} $(opt_type f)\n"
	echo -e "${WHITE_FG}-H${RESET} help"
	echo -e "${WHITE_FG}-D${RESET} debug"
	echo -e "${WHITE_FG}\nDESC${RESET}:${DESC}"

	exit_leave $(msg_err ${PENDING_MSGS})
}

typeset -a OPTIONS
OPTSTR=":HD"
OPTIND=0

while getopts ${OPTSTR} OPTION;do
	case $OPTION in
     H) usage;;
     D) dbg_set_level;;
     :) print -u2 "${RED_FG}${_SCRIPT}${RESET}: option: -${OPTARG} requires an argument"; usage;;
    \?) print -u2 "${RED_FG}${_SCRIPT}${RESET}: unknown option -${OPTARG}"; usage;;
	esac
	[[ ${OPTION} != 'D' ]] && OPTIONS+=${OPTION}
done
shift $((OPTIND -1))
#--End GetOpts--
#Execution
[[ ${#} -eq 0 ]] && usage
[[ ${_DEBUG} -gt 0 ]] && set -xv

RC=0
LIST=($@)
for F in ${LIST};do
	[[ ! -e ${F} ]] && echo "File:${WHITE_FG}${F}${RESET} ${RED_FG}not found${RESET}" && continue
	case ${F:e} in
		odg) ${OFFICE} ${F} 2>/dev/null;;
		ods) ${OFFICE} ${F} 2>/dev/null;;
		xls) ${OFFICE} ${F} 2>/dev/null;;
		odt) ${OFFICE} ${F} 2>/dev/null;;
		doc) ${OFFICE} ${F} 2>/dev/null;;
		txt) ${OFFICE} ${F} 2>/dev/null;;
		*) echo "No office app configured to handle files of type:${WHITE_FG}$(file ${F})${RESET}";RC=1;;
	esac
done

[[ ${_DEBUG} -gt 0 ]] && set +xv

exit_leave
