#!/usr/bin/zsh
#Inline ansi
BOLD="\033[1m"
ITALIC="\033[3m"
RESET="\033[m"
REVERSE="\033[7m"
STRIKE="\033[9m"
UNDER="\033[4m"

BLUE_FG="\033[34m"
CYAN_FG="\033[36m"
GREEN_FG="\033[32m"
MAGENTA_FG="\033[35m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"
YELLOW_FG="\033[33m"

#Declarations
_LIB=/usr/local/lib

#Imports
source ${_LIB}/common.zsh

#Constants
_VID_REGEX_Z='.*\.(mp4|avi|mkv)$'
_VID_REGEX_F='.*\.\(mp4\|avi\|mkv\)$'

#Functions
usage () {

	tabs 5
	[[ ${_SMCUP} == 'true' ]] && do_rmcup

	echo "\nUsage: ${_SCRIPT} <FILE>|<FILELIST>\n"

	exit_leave
}

trim () {
	local LINE

	while read LINE;do
		echo ${LINE} | sed -e 's/^ *//' -e 's/ *$//'
	done
}

do_info () {
	local LIST=("${(f)$(ffprobe ${1}  2>&1 | grep -i 'duration\|stream')}")

	local DUR=Duration:None
	local VID=Video:None
	local AUD=Audio:None
	local RES=None
	local SUB=false
	local DESC
	local VAL
	local HDR
	local -a INFO
	local L I

	for L in ${LIST};do
		[[ ${_DEBUG} -gt 0 ]] && dbg "L: ${L}"
		[[ ${L:l} =~ 'subtitle:' ]] && SUB=true
		[[ ${L:l} =~ 'duration:' ]] && DUR=$(perl -p -e 's/(\s+)([^,]+)(.*)/$2/i' <<<${L})
		[[ ${L:l} =~ "video:" ]] && RES=$(perl -p -e 's/^(.*)(?<=[ ,])(\d+x\d+)(?=[ ,])(.*)$/$2/g' <<<${L})
		[[ ${L:l} =~ "video:" ]] && VID=$(perl -pe 's/^(.*)(vid.*?)(?=[,(])(.*)/$2/i' <<<${L})
		[[ ${L:l} =~ "audio:" ]] && AUD=$(perl -pe 's/^(.*)(aud.*?)(?=[,(])(.*)/$2/i' <<<${L})
	done

	[[ ${SUB} == 'true' ]] && SUB="yes" || SUB="no"
	[[ ${AUD} != 'Audio:None' ]] && AUD=${AUD:u}
	DUR=$(sed 's/[0]+$//' <<<${DUR})

	INFO=("${(C)DUR}" "${(C)VID}" "Resolution:${RES}" "${AUD}" "Subtitiles:${(C)SUB}")

	HDR="\nVideo Information: ${WHITE_FG}${@:t}${RESET}"
	echo ${HDR}
	HDR=$(echo ${HDR} | str_strip_ansi -l)
	echo $(str_unicode_line ${HDR})

	for I in ${INFO};do
		DESC=${$(cut -d: -f1 <<<${I} | trim):=None}
		VAL=$(cut -d: -f2- <<<${I} | trim)
		printf "${CYAN_FG}%20s${RESET}: ${WHITE_FG}%-20s${RESET}\n" ${(C)DESC} ${VAL}
	done

	echo
}

#--Begin GetOpts--
RESET="\033[m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"

read -r -d '' DESC<<EOF
Provide essential info about video files
EOF

parse_opts () {
	local OPTS=${@}
	local -a OPTSTRING
	local LETTER_OPT
	local O

	for O in {1..${#OPTS}};do
		[[ ${OPTS[${O}]} =~ '[a-z]' ]] && LETTER_OPT=${OPTS[${O}]}
		[[ ${O} -eq 1 && ${OPTS[${O}]} == ":" ]] && continue
		[[ ${O} -gt 1 && ${OPTS[${O}]} == ":" ]] && OPTSTRING+=$(opt_type ${LETTER_OPT}) && continue
		OPTSTRING+="-${OPTS[${O}]}"
	done
	echo ${OPTSTRING}
}

opt_exists () {
	local OPT=${1}
	[[ $(( $OPTIONS[(Ie)${OPT}] )) -ne 0 ]] && return 0 || return 1
}

opt_type () {
	local OPT=${1}
	case ${OPT} in
		d) echo "<DIR>";;
		f) echo "<FILE>";;
		t) echo "<FILE_TYPE>";;
	esac
}

usage () {
	tabs 5
	local OPTS=$(parse_opts ${OPTSTR})
	local -a PENDING_MSGS=(${@})
	echo -e "\n${WHITE_FG}Usage${RESET}: ${_SCRIPT} ${WHITE_FG}[${RESET}${OPTS}${WHITE_FG}]${RESET}\n"
	echo -e "${WHITE_FG}-H${RESET} help"
	echo -e "${WHITE_FG}-D${RESET} debug"
	echo -e "\n${WHITE_FG}DESC${RESET}:${DESC}"

	exit_leave $(msg_err ${PENDING_MSGS})
}

typeset -a OPTIONS
OPTSTR=":HD"
OPTIND=0

while getopts ${OPTSTR} OPTION;do
	case $OPTION in
     H) usage;;
     D) dbg_set_level;;
     :) print -u2 "${RED_FG}${_SCRIPT}${RESET}: option: -${OPTARG} requires an argument"; usage;;
    \?) print -u2 "${RED_FG}${_SCRIPT}${RESET}: unknown option -${OPTARG}"; usage;;
	esac
	[[ ${OPTION} != 'D' ]] && OPTIONS+=${OPTION}
done
shift $((OPTIND -1))
#--End GetOpts--

#Execution
if [[ ${#} -eq 0 ]];then
	LIST=("${(f)$(find . -maxdepth 1 -type f -regex "${_VID_REGEX_F}")}")
else
	LIST=(${@})
fi

HIT=false
for L in ${LIST};do
	[[ ! ${L} =~ ${_VID_REGEX_Z} ]] && continue
	[[ -d ${L} ]] && continue
	HIT=true
	do_info ${L}
done

[[ ${HIT} == 'false' ]] && usage "No video files found in ${PWD}"

exit_leave
