#!/usr/bin/zsh
#vim: syntax off
RESET="\033[m"
BOLD="\033[1m"
ITALIC="\033[3m"
UNDER="\033[4m"
REVERSE="\033[7m"
STRIKE="\033[9m"

RED_FG="\033[31m"
GREEN_FG="\033[32m"
YELLOW_FG="\033[33m"
BLUE_FG="\033[34m"
MAGENTA_FG="\033[35m"
CYAN_FG="\033[36m"
WHITE_FG="\033[37m"

for FN in *;do 
	if [[ $(file ${FN}) =~ "audio" ]];then
		[[ -e ${FN:r}.wav ]] && rm -f ${FN:r}.wav
		echo "Converting:${WHITE_FG}${FN}${RESET}"
		soundconverter -b -m "audio/x-wav" -s '.wav' ${FN} 2>CONV_MSGS
		RC=${?}
		[[ ${RC} -ne 0 ]] && echo "${RED_FG}ERROR${RESET}:" && cat CONV_MSGS
	fi
done
rm -f CONV_MSGS
