#!/usr/bin/zsh
#Inline ansi
BOLD="\033[1m"
ITALIC="\033[3m"
RESET="\033[m"
REVERSE="\033[7m"
STRIKE="\033[9m"
UNDER="\033[4m"

BLUE_FG="\033[34m"
CYAN_FG="\033[36m"
GREEN_FG="\033[32m"
MAGENTA_FG="\033[35m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"
YELLOW_FG="\033[33m"

read -r -d '' DESC<<EOF
Convert mp3 to wav
EOF

if [[ ${#} -eq 0 ]];then
	echo "Usage:${0} <MP3>"
	echo "${WHITE_FG}\nDESC${RESET}:${DESC}"
	exit
fi

for fn in ${@};do
    basefn=$(basename ${fn} .mp3)
    echo "Converting: ${basefn}.mp3 to ${basefn}.wav"
    ffmpeg -i ${basefn}.mp3 ${basefn}.wav
done
