#!/usr/bin/zsh
REVERSE="\033[7m"
RESET="\033[m"
BOLD="\033[1m"
BLACK_FG="\033[30m"
RED_FG="\033[31m"
GREEN_FG="\033[32m"
YELLOW_FG="\033[33m"
BLUE_FG="\033[34m"
MAGENTA_FG="\033[35m"
CYAN_FG="\033[36m"
WHITE_FG="\033[37m"

function leave {
	[[ ${1} == "error" ]] && echo "${0} had errors, exiting..."
	kill -SIGINT $$ 
}

only_comments () {
	IFS=''
	while read LINE;do
		[[ ${LINE} =~ '^#' ]] && printf '%s\n' "${LINE}"
	done
}

filter_comments () {
	IFS=''
	while read -r LINE;do
		if [[ -n ${LINE} && ! ${LINE} =~ '^#' ]];then
			if [[ ${DEBUG} == 'true' ]];then
				echo ">>>"
				echo "${LINE}" | xxd -c 1
				echo "<<<"
			fi
			printf '%s\n' "${LINE}"
		fi
	done
}

#--Begin GetOpts--
RESET="\033[m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"

SCRIPT=${0:t}
parse_opts () {
	local OPTS=${@}
	local -a OPTSTRING
	local LETTER_OPT
	local O

	for O in {1..${#OPTS}};do
		[[ ${OPTS[${O}]} =~ '[a-z]' ]] && LETTER_OPT=${OPTS[${O}]}
		[[ ${O} -eq 1 && ${OPTS[${O}]} == ":" ]] && continue
		[[ ${O} -gt 1 && ${OPTS[${O}]} == ":" ]] && OPTSTRING+=$(opt_type ${LETTER_OPT}) && continue
		OPTSTRING+="-${OPTS[${O}]}"
	done
	echo ${OPTSTRING}
}

opt_type () {
	local OPT=${1}
	case ${OPT} in
		d) echo "<DIR>";;
		f) echo "<FILE>";;
		t) echo "<FILE_TYPE>";;
	esac
}


read -r -d '' DESC<<EOF
Displays content with comments filtered or shows only the comments
\tActs as a filter or a file name can be passed
EOF

usage () {
	local OPTS=$(parse_opts ${OPTSTR})

	tabs 5

	echo -e "${WHITE_FG}Usage${RESET}: ${SCRIPT} ${WHITE_FG}[${RESET}${OPTS}${WHITE_FG}]${RESET} [<FILE>]\n"
	echo -e "${WHITE_FG}-H${RESET} help"
	echo -e "${WHITE_FG}-D${RESET} debug"
	echo -e "${WHITE_FG}-n${RESET} hide all comments (default)"
	echo -e "${WHITE_FG}-o${RESET} show only comments"
	echo -e "${WHITE_FG}\nDESC${RESET}:${DESC}"

	leave
}

OPTSTR=":HDno"

DEBUG=false
HIDE_COMMENTS=false
SHOW_COMMENTS=false
OPTIND=0
while getopts ${OPTSTR} OPTION;do
	case $OPTION in
     H) usage;;
     D) DEBUG=true;;
     n) HIDE_COMMENTS=true;;
     o) SHOW_COMMENTS=true;;
     :) print -u2 "${SCRIPT}: option: -${OPTARG} requires an argument"; usage;;
    \?) print -u2 "${SCRIPT}: unknown option -${OPTARG}"; usage;;
	esac
done
shift $((OPTIND -1))
#--End GetOpts--
#Execution
[[ -t 0 && ${#} -eq 0 ]] && usage #no args - needs file or pipe

[[ ${HIDE_COMMENTS} == 'false' && ${SHOW_COMMENTS} == 'false' ]] && HIDE_COMMENTS=true #default

if [[ ${#} -eq 1 ]];then #file arg
	if [[ -e ${1} ]];then
		FN=$1
	else
		echo "${1}: file not found"
		usage
	fi
fi

if [[ ! -t 0 ]];then
	[[ ${HIDE_COMMENTS} == 'true' ]] && filter_comments "$@"
	[[ ${SHOW_COMMENTS} == 'true' ]] && only_comments "$@"
else
	[[ ${HIDE_COMMENTS} == 'true' ]] && filter_comments <${FN}
	[[ ${SHOW_COMMENTS} == 'true' ]] && only_comments <${FN}
fi

