#!/usr/bin/zsh
REVERSE="\033[7m"
RESET="\033[m"
BOLD="\033[1m"
BLACK_FG="\033[30m"
RED_FG="\033[31m"
GREEN_FG="\033[32m"
YELLOW_FG="\033[33m"
BLUE_FG="\033[34m"
MAGENTA_FG="\033[35m"
CYAN_FG="\033[36m"
WHITE_FG="\033[37m"

#Globals
g_TARGET_DIR=$(pwd)
 
is_empty_dir () {
	local DIR=${1}

	[[ -d ${DIR} ]] && return $(find ${DIR} -maxdepth 1 ! -path ${1} | wc -l)
}

get_response () {
	local RESPONSE

	if [[ ${NOPROMPT} = false ]];then
		read -q RESPONSE
	fi
	echo

	[[ ${RESPONSE:l} = "y" ]] && return 0 || return 1
} 

is_image () {
	local RVAL

	case ${1:l} in
		jpg) RVAL=0;;
		png) RVAL=0;;
		svf) RVAL=0;;
		*) RVAL=1;;
	esac

	return ${RVAL}
}

is_junk () {
	local RVAL

	case ${1:l} in
		*exe) RVAL=0;;
		etrg*) RVAL=0;;
		*txt) RVAL=0;;
		*mov) RVAL=0;;
		*nfo) RVAL=0;;
		*svf) RVAL=0;;
		*readme*) RVAL=0;;
		*sample*) RVAL=0;;
		*swe*srt) RVAL=0;;
		*url) RVAL=0;;
		*vtx) RVAL=0;;
		*torrent) RVAL=0;;
		*) RVAL=1;;
	esac

	return ${RVAL}
}

process_dir () {
	local DIR=${1}
	local MOVE=true
	local NOMOVE
	local MODE
	local MSG
	local RC
	local TARGET_DIR_MSG
	local I
	local NDX=0

	[[ -n ${g_TARGET_DIR} ]] && TARGET_DIR_MSG=${g_TARGET_DIR} || TARGET_DIR_MSG="current directory"

	is_empty_dir ${DIR}
	RC=$?
	
	if [[ ${RC} -eq 0 ]];then
		echo "${YELLOW_FG}Skipped empty dir:${GREEN_FG}${1}${RESET}"
		return #skip empty dirs in the current dir
	else
		if [[ ${NOPROMPT} = false ]];then
			echo -n "Should files from ${GREEN_FG}${1}${RESET} be moved to ${TARGET_DIR_MSG}? (y/n):"
			if ! get_response;then
				echo "Operation cancelled"
				exit
			fi
		fi
	fi

	for I in ${DIR}/*;do
		if [[ -d ${I} ]];then
			process_dir ${I}
		else
			MSG=''
			((NDX++))
			if [[ ${RMTORRENTJUNK} == "true" ]];then
				if [[ ${SIMULATE} == "true" ]];then
					echo "SIMULATING -> is_junk ${I:t:l}"
					if is_junk ${I:t:l};then
						echo "${I} is junk - would be discarded"
					else
						echo "NOT junk - would be kept"
					fi
					echo "SIMULATING -> is_junk ${I:e}"
					if is_junk ${I:e};then
						echo "${I} is junk - would be discarded"
					else
						echo "NOT junk - would be kept"
					fi
					echo "SIMULATING -> is_image ${I:e}"
					if is_image ${I:e};then
						echo "${I} is image - would be discarded"
					else
						echo "NOT junk - would be kept"
					fi
				else
					MSG="junk"
					MODE="discarded"
					NOMOVE=false
					if is_junk ${I:t:l};then
						/bin/rm -f ${I} 
						NOMOVE=true
					fi
					if is_junk ${I:e};then
						/bin/rm -f ${I}
						NOMOVE=true
					fi
					if is_image ${I:e};then
						/bin/rm -f ${I}
						NOMOVE=true
					fi
				fi
			fi

			if [[ ${NOMOVE} == "false" ]];then
				if [[ -e ${g_TARGET_DIR}/${I:t} ]];then
					NOMOVE=true
					MSG="${RED_FG}Error${RESET}:would overwrite existing file:${GREEN_FG}./${WHITE_FG}${I:t}${RESET}"
					MODE="NOT moved"
				else
					MSG="${WHITE_FG}surfaced${RESET}"
					MODE="moved"
				fi
			fi

			case ${MODE:l} in
				discarded) ACTION_COLOR=${RED_FG};;
				moved) ACTION_COLOR=${GREEN_FG};;
				"not moved") ACTION_COLOR=${RED_FG};;
				*) ACTION_COLOR='';;
			esac

			[[ ${MODE} == 'discarded' ]] && ACTION_COLOR=${RED_FG} || ACTION_COLOR=''
			printf "\nProcessing dir:${WHITE_FG}%s${RESET}\nFile ("%02d") ${BOLD}${ACTION_COLOR}"'%10s'"${RESET}:${GREEN_FG}%s${RESET}/${WHITE_FG}%s${RESET} -> "'%s'"${RESET}" ${DIR} ${NDX} ${(C)MODE} ${I:h} ${I:t} "$(echo ${MSG})"

			[[ ${NOMOVE} == "true" ]] && continue

			if [[ ${NOPROMPT} = true ]] || [[ ${MOVE} -eq 0 ]];then
				if [[ ${SIMULATE} == "true" ]];then
					echo "SIMULATING -> mv ${I} ${g_TARGET_DIR}"
				else
					mv ${I} ${g_TARGET_DIR}
				fi
				[[ $? -ne 0 ]] && echo "Error:Move was unsuccessful" >@2
			fi
		fi
	done
	echo
}

#--Begin GetOpts--
RESET="\033[m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"

read -r -d '' DESC<<EOF
Move files from a sub directory up to the current dir (default action)
\tThe sub directory indicated will then be deleted upon the successful
\trelocation of its files. This behaviour can be altered through the use 
\tof options. Torrent junk files are discarded by default.
EOF

parse_opts () {
	local OPTS=${@}
	local -a OPTSTRING
	local LETTER_OPT
	local O

	for O in {1..${#OPTS}};do
		[[ ${OPTS[${O}]} =~ '[a-z]' ]] && LETTER_OPT=${OPTS[${O}]}
		[[ ${O} -eq 1 && ${OPTS[${O}]} == ":" ]] && continue
		[[ ${O} -gt 1 && ${OPTS[${O}]} == ":" ]] && OPTSTRING+=$(opt_type ${LETTER_OPT}) && continue
		OPTSTRING+="-${OPTS[${O}]}"
	done
	echo ${OPTSTRING}
}

opt_exists () {
	local OPT=${1}
	[[ $(( $OPTIONS[(Ie)${OPT}] )) -ne 0 ]] && return 0 || return 1
}

opt_type () {
	local OPT=${1}
	case ${OPT} in
		d) echo "<DIR>";;
		t) echo "<TARGET DIR>";;
	esac
}

usage () {

	tabs 5
	[[ ${_SMCUP} == 'true' ]] && do_rmcup

	local OPTS=$(parse_opts ${OPTSTR})
	local -a PENDING_MSGS=(${@})

	echo -e "\n${WHITE_FG}Usage${RESET}: $SCRIPT ${WHITE_FG}[${RESET} $OPTS ${WHITE_FG}]${RESET} $(opt_type d)\n"
	echo -e "${WHITE_FG}-H${RESET} help"
	echo -e "${WHITE_FG}-D${RESET} debug"
	echo -e "${WHITE_FG}-i${RESET} interactive prompts"
	echo -e "${WHITE_FG}-t $(opt_type t)${RESET} dir to hold surfaced files"
	echo -e "${WHITE_FG}-d${RESET} do not remove empty dirs"
	echo -e "${WHITE_FG}-j${RESET} do not remove junk files from torrent directories"
	echo -e "${WHITE_FG}-s${RESET} simulate actions only"
	echo -e "\n${WHITE_FG}DESC${RESET}:${DESC}\n"

	exit
}

typeset -a OPTIONS
OPTSTR=":DHit:djs"
OPTIND=0
DEBUG=false
NOPROMPT=true
DELDIRS=true
RMTORRENTJUNK=true
SIMULATE=false

while getopts ${OPTSTR} OPTION;do
	case $OPTION in
     H) usage;;
     D) DEBUG=true;;
     i) NOPROMPT=false;;
     t) g_TARGET_DIR=${OPTARG};;
     d) DELDIRS=false;;
     j) RMTORRENTJUNK=false;;
     s) SIMULATE=true;;
     :) print -u2 "${SCRIPT}: option: -${OPTARG} requires an argument"; usage;;
    \?) print -u2 "${SCRIPT}: unknown option -${OPTARG}"; usage;;
	esac

	[[ ${OPTION} != 'D' ]] && OPTIONS+=${OPTION}
done
shift $((OPTIND -1))
#--End GetOpts--

#---Execution---

if [[ $# -eq 0 ]];then
	echo -n "${RED_FG}Warning${RESET}: this will effect ALL sub-directories under:${WHITE_FG}${PWD}${RESET}. Proceed (y/n)?:"
	read -sq RESPONSE
	[[ ${RESPONSE} != 'y' ]] && exit
	DIRS=("${(@f)$(find ./* -type d)}")
else
	DIRS=($@)
fi

echo "${WHITE_FG}Target Directory${RESET}:${g_TARGET_DIR}"

for D in ${DIRS};do
	[[ ! -d ${D} ]] && echo "Warning: Skipping \"${DIRS}\". Not a directory!" && continue
	echo "Processing:${WHITE_FG}$(realpath ${D})${RESET}"
	process_dir ${D}
	if [[ ${NOPROMPT} = true ]];then
		if [[ ${DELDIRS} = true ]];then
			FILE_COUNT=$(find ${D} ! -path ${D} -type f | wc -l)
			if [[ ${FILE_COUNT} -eq 0 ]];then
				if [[ ${SIMULATE} == "true" ]];then
					echo "SIMULATING -> /bin/rm -rf ${D} >/dev/null 2>&1"
				else
					/bin/rm -rf ${D} >/dev/null 2>&1
					echo "Original Directory:${WHITE_FG}$(realpath ${D} | pathabv)${RESET} was removed."
				fi
			else
				echo "Original Directory:${WHITE_FG}${D}${RESET} contains ${WHITE_FG}${FILE_COUNT}${RESET} files and could not be removed."
			fi
		fi
	else
		echo -n "Remove directory ${WHITE_FG}${D}${RESET}?..(y/n)?:"
		if get_response;then
			echo "Removing ${WHITE_FG}${D}${RESET}"
			/bin/rm -rf ${D} >/dev/null 2>&1
		else
			echo "Operation cancelled"
			exit
		fi
	fi  
done
