#!/usr/bin/zsh
RESET="\033[m"
RED_FG="\033[31m"
GREEN_FG="\033[32m"
YELLOW_FG="\033[33m"
BLUE_FG="\033[34m"
MAGENTA_FG="\033[35m"
CYAN_FG="\033[36m"
WHITE_FG="\033[37m"

E_REVERSE=$(echo "\033[7m")
E_RESET=$(echo "\033[m")
E_BOLD=$(echo "\033[1m")
E_BLACK_FG=$(echo "\033[30m")
E_RED_FG=$(echo "\033[31m")
E_GREEN_FG=$(echo "\033[32m")
E_YELLOW_FG=$(echo "\033[33m")
E_BLUE_FG=$(echo "\033[34m")
E_MAGENTA_FG=$(echo "\033[35m")
E_CYAN_FG=$(echo "\033[36m")
E_WHITE_FG=$(echo "\033[37m")

SITE=www.google.com
WLESS=wlo1
typeset -a ACTIVE_IFACES

prompt () {
	printf "\n${WHITE_FG}Continue?${RESET}:"
	read -q RESPONSE
	[[ ${RESPONSE} == "n" ]] && exit
}

TEST=false
[[ $1 == "-t" ]] && TEST=true && shift

FULL=false
[[ $1 == "-f" ]] && FULL=true && shift

#get interface
ACTIVE_IFACES=($(ifconfig -v | grep 'RUNNING.*MULTICAST' | cut -d: -f1))
[[ -z ${ACTIVE_IFACES} ]] && echo "${RED_FG}Unable to detect an active interface${RESET}.\nVerify wifi or cable connection" && exit

#get DNS
typeset -A DNS
VPN_DNS=false
for I in ${ACTIVE_IFACES};do 
	if [[ $I =~ "tun" ]];then
		LIST=()
		LIST=($(cat /etc/resolv.conf | grep "^nameserver" | cut -d' ' -f2))
		VPN_DNS=true
		break
	else
		LIST+=($(nmcli device show $I | grep IP4.DNS | tr -s '[:space:]' | cut -d: -f2))
	fi
done

NDX=0
for D in ${LIST};do
	((NDX++))
	DNS[DNS${NDX}]=$D
done

clear

echo "Working..."

printf "${WHITE_FG}Hostname ($(which hostname))${RESET}: %-s\n" $(hostname)
printf "${WHITE_FG}Active Interface (ifconfig)${RESET}: %-s\n" $(for I in ${ACTIVE_IFACES};do echo $I;done)
printf "${WHITE_FG}Site used for testing:${RESET}: %-s\n" ${SITE}

LANIP=$(ip_int | head -1)
EXTIP=$(ip_ext)

[[ -z ${LANIP} ]] && echo "Unable to obtain Local Area Network IP Address. Check basic connectivity" && exit
[[ -z ${EXTIP} ]] && echo "Unable to obtain External Network IP Address. Check basic connectivity" && exit

printf "\n${WHITE_FG}IP Information ($(which host))${RESET}\n"
printf "Machine Internal IP: %s\n" ${LANIP}
printf "Machine External IP: %s\n" ${EXTIP}

host $SITE

printf "\n${WHITE_FG}/etc/hosts configuration (/etc/hosts)${RESET}\n"
cat /etc/hosts

printf "\n${WHITE_FG}Interface Configuration ($(which ifconfig))${RESET}\n"
ifconfig 2>&1

if [[ ${ACTIVE_IFACES[(i)${WLESS}]} -le ${#ACTIVE_IFACES} ]];then #${WLESS} is present in array of active interfaces
	printf "\n${WHITE_FG}Wireless Interface Configuration ($(which iwconfig))${RESET}\n"
	iwconfig  2>&1
	printf "\n${WHITE_FG}Wireless Channel Info ($(which iwlist))${RESET}\n"
	sudo iwlist ${WLESS} scan | grep -i 'freq\|ssid' | sed 's/[\t ]*//g' 
fi

printf "\n${WHITE_FG}Contents of /etc/resolv.conf${RESET}\n"
cat /etc/resolv.conf

if [[ ${VPN_DNS} == "true" ]];then
	echo "${GREEN_FG}VPN is active${RESET}" 2>&1
	printf "${WHITE_FG}GEO Location ($(which geo))${RESET}\n"
	geo 2>&1
	echo "${WHITE_FG}\nGathered VPN DNS IP's (/etc/resolv.conf)${RESET}:${#DNS}" 2>&1
else
	echo "${WHITE_FG}\nGathered DNS IP's ($(which nmcli))${RESET}:${#DNS}" 2>&1
fi

for D in ${(k)DNS};do
	printf "\n${WHITE_FG}$D (${DNS[${D}]}) Ping Time ($(which ping))${RESET}\n"
	ping -c3 ${DNS[${D}]}
done

printf "\n${WHITE_FG}Internet Ping Time ($(which ping))${RESET}\n"
ping -c3 $SITE

printf "\n${WHITE_FG}NSLOOKUP ($(which nslookup))${RESET}\n"
nslookup $SITE

printf "\n${WHITE_FG}ARP Information ($(which arp))${RESET}\n"
arp -e | head -1
arp -e | tail +2 | sort

printf "\n${WHITE_FG}Enhanced ARP Information ($(which lan_devices))${RESET}\n"
lan_devices -i

printf "\n${WHITE_FG}Route ($(which route))${RESET}\n"
route

printf "\n${WHITE_FG}Current Open Ports ($(which ss))${RESET}\n"
sudo ss -r -ltup | sort -k1.91 -k1.52n

printf "\n${WHITE_FG}Network Manager Settings ($(which nmcli))${RESET}\n"
nmcli -t dev show

if [[ -e /proc/net/bonding/bond0 ]];then
	printf "\n${WHITE_FG}Network Bonding Info (/proc/net/bonding/bond0)${RESET}\n"
	cat /proc/net/bonding/bond0
fi

if [[ $TEST == "true" ]];then
	printf "\n${WHITE_FG}Speedtest Requested ($(which speedtest-cli))${RESET}\n"
	speedtest-cli
fi
