#!/usr/bin/zsh
REVERSE="\033[7m"
RESET="\033[m"
BOLD="\033[1m"
BLACK_FG="\033[30m"
RED_FG="\033[31m"
GREEN_FG="\033[32m"
YELLOW_FG="\033[33m"
BLUE_FG="\033[34m"
MAGENTA_FG="\033[35m"
CYAN_FG="\033[36m"
WHITE_FG="\033[37m"

for F in $@;do
	unfunction $F &> /dev/null
	[[ $? -ne 0 ]] && echo "Ignoring:${RED_FG}$F${RESET} - undefined" && continue
	autoload $F
	echo "${GREEN_FG}${F}${RESET} has been refreshed"
done

