#!/usr/bin/zsh

REVERSE="\033[7m"
RESET="\033[m"
BOLD="\033[1m"
BLACK_FG="\033[30m"
RED_FG="\033[31m"
GREEN_FG="\033[32m"
YELLOW_FG="\033[33m"
BLUE_FG="\033[34m"
MAGENTA_FG="\033[35m"
CYAN_FG="\033[36m"
WHITE_FG="\033[37m"

#Constants
ME=${0:t}
DEFAULT=$(date +"%Y-%m-%d")
LOGS=("${(f)$(find /var/log/dpkg.log*)}") 

#--Begin GetOpts--
RESET="\033[m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"

SCRIPT=${0:t}
function parse_opts {
	local OPTS=$@
	local -a OPTSTRING
	for O in {1..${#OPTS}};do
		[[ $O -eq 1 && ${OPTS[$O]} == ":" ]] && continue
		[[ $O -gt 1 && ${OPTS[$O]} == ":" ]] && OPTSTRING+="<PARAM>" && continue
		OPTSTRING+="-${OPTS[$O]}"
	done
	echo $OPTSTRING
}

usage () {
	echo "Usage:${WHITE_FG}${ME}${RESET} date-criterion | keyword (partial ok) i.e \"grub, purge, install\"" echo "Date is in form:${WHITE_FG}${DEFAULT}${RESET}"
	echo "Partial dates are allowed:${WHITE_FG}${DEFAULT[1,2]}${RESET}"
	echo "                          ${WHITE_FG}${DEFAULT[1,3]}${RESET}"
	echo "                          ${WHITE_FG}${DEFAULT[1,4]}${RESET}"
	echo "                          ${WHITE_FG}${DEFAULT[1,6]}${RESET}"
	echo "                          ${WHITE_FG}${DEFAULT[1,7]}${RESET}"
	echo "                          ${WHITE_FG}${DEFAULT[1,9]}${RESET}"
	echo "                          ${WHITE_FG}${DEFAULT[1,10]}${RESET} etc..."
	echo "Default is today:${WHITE_FG}${DEFAULT}${RESET}"
	echo "Desc:${WHITE_FG}show all dpkg activity for date range specified (day,month,year) or any grep-able keyword${RESET}"
	exit
}

OPTSTR=":HD:"

DEBUG=false
OPTIND=0
while getopts ${OPTSTR} OPTION;do
	case $OPTION in
     H) usage;;
     D) DEBUG=true;;
     :) print -u2 "${SCRIPT}: option: -${OPTARG} requires an argument"; usage;;
    \?) print -u2 "${SCRIPT}: unknown option -${OPTARG}"; usage;;
	esac
done
shift $((OPTIND -1))
#--End GetOpts--

#Execution
DATEARG=${1:=${DEFAULT}}

PRELIST=$(zgrep -h ${DATEARG} $LOGS | sed -e 's/status //g' -e '/startup/d')
LIST=("${(f)$(echo ${PRELIST} | zgrep -hP "\sinstalled|remove|purge" | cut -d' ' -f1,3- | sort -u)}") 
[[ -z ${LIST} ]] && echo "No activity for ${WHITE_FG}${DATEARG}${RESET}" && exit
[[ ${DATEARG} == ${DEFAULT} ]] && MSG="Last update" || MSG=" Updated on"

LASTDATE=?
for L in ${LIST};do
	LDATE=$(echo $L | cut -d' ' -f1)
	LLINE=$(echo $L | cut -d' ' -f2-)
	if [[ ${LASTDATE} != ${LDATE} ]];then
		echo "----------------------"
		echo ${MSG}:${WHITE_FG}${LDATE}${RESET}
		echo "----------------------"
		LASTDATE=${LDATE}
	fi
	LEADING=$(echo ${LLINE} | cut -d' ' -f1)
	TRAILING=$(echo ${LLINE} | cut -d' ' -f2-)
	case ${LEADING} in
		*installed*) echo "${GREEN_FG}${LEADING} ${WHITE_FG}${TRAILING}${RESET}";;
		*remove*) echo "${RED_FG}   ${LEADING} ${WHITE_FG}${TRAILING}${RESET}";;
		*purge*) echo "${BOLD}${RED_FG}    ${LEADING} ${WHITE_FG}${TRAILING}${RESET}";;
		*) echo ${LLINE};;
	esac
done >/tmp/updates.out
cat /tmp/updates.out | mypager
