#!/usr/bin/zsh
RESET="\033[m"
RED_FG="\033[31m"
GREEN_FG="\033[32m"
YELLOW_FG="\033[33m"
BLUE_FG="\033[34m"
MAGENTA_FG="\033[35m"
CYAN_FG="\033[36m"
WHITE_FG="\033[37m"
BOLD="\033[1m"

#Constants

#--Begin GetOpts--
RESET="\033[m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"

SCRIPT=${0:t}
parse_opts () {
	local OPTS=${@}
	local -a OPTSTRING
	local LETTER_OPT
	for O in {1..${#OPTS}};do
		[[ ${OPTS[${O}]} =~ '[a-z]' ]] && LETTER_OPT=${OPTS[${O}]}
		[[ ${O} -eq 1 && ${OPTS[${O}]} == ":" ]] && continue
		[[ ${O} -gt 1 && ${OPTS[${O}]} == ":" ]] && OPTSTRING+=$(opt_type ${LETTER_OPT}) && continue
		OPTSTRING+="-${OPTS[${O}]}"
	done
	echo ${OPTSTRING}
}

opt_type () {
	local OPT=${1}
	case ${OPT} in
		d) echo "<SERVICE>";;
		e) echo "<SERVICE>";;
		S) echo "<SERVICE>";;
		s) echo "<SERVICE>";;
		v) echo "<SERVICE>";;
	esac
}

function usage {
	local OPTS=$(parse_opts $OPTSTR)
   echo -e "\n${WHITE_FG}Usage${RESET}: $SCRIPT ${WHITE_FG}[${RESET} $OPTS ${WHITE_FG}]${RESET} [SEARCHTERM]\n"
   echo -e "${WHITE_FG}-H${RESET} help"
	echo -e "${WHITE_FG}-D${RESET} debug"
	echo -e "${WHITE_FG}-a${RESET} Show all units (active or inactive)"
	echo -e "${WHITE_FG}-d $(opt_type d)${RESET} Disable"
	echo -e "${WHITE_FG}-e $(opt_type e)${RESET} Enable"
	echo -e "${WHITE_FG}-r${RESET} Daemon Reload"
	echo -e "${WHITE_FG}-S $(opt_type S)${RESET} Stop"
	echo -e "${WHITE_FG}-s $(opt_type s)${RESET} Start"
	echo -e "${WHITE_FG}-v $(opt_type v)${RESET} View"
    echo -e "\n${WHITE_FG}DESC${RESET}:Trivial frontend for systemctl to do basic tasks.\n"
	exit
}

OPTSTR=":HDard:e:S:s:v:"

DEBUG=false
OPTIND=0
ALL_SERVICES=false
DISABLE=false
ENABLE=false
START=false
STOP=false
STATUS=false
DAEMON_RELOAD=false
while getopts ${OPTSTR} OPTION;do
	case $OPTION in
     H) usage;;
     D) DEBUG=true;;
     a) ALL_SERVICES=true;;
     d) DISABLE=true;SERVICE=${OPTARG};;
     e) ENABLE=true;SERVICE=${OPTARG};;
     S) STOP=true; SERVICE=${OPTARG};;
     s) START=true; SERVICE=${OPTARG};;
     v) STATUS=true; SERVICE=${OPTARG};;
     :) print -u2 "${SCRIPT}: option: -${OPTARG} requires an argument"; usage;;
    \?) print -u2 "${SCRIPT}: unknown option -${OPTARG}"; usage;;
	esac
done
shift $((OPTIND -1))
#--End GetOpts--

#Execution
SEARCH=false
[[ -n ${1} ]] && SEARCHTERM=${1} && SEARCH=true

DEFAULT_ARGS='list-units --state=active'

if [[ ${ALL_SERVICES} == 'true' ]];then
	ARGS="--plain list-units --all"
elif [[ ${STOP} == 'true' ]];then
	ARGS="stop ${SERVICE}"
elif [[ ${START} == 'true' ]];then
	ARGS="start ${SERVICE}"
elif [[ ${STATUS} == 'true' ]];then
	ARGS="status ${SERVICE}"
elif [[ ${SEARCH} == 'true' ]];then
	ARGS="--plain list-units --all | grep --color=always ${SEARCHTERM}"
elif [[ ${DAEMON_RELOAD} == 'true' ]];then
	ARGS="daemon-reload"
elif [[ ${DISABLE} == 'true' ]];then
	ARGS="disable ${SERVICE}"
elif [[ ${ENABLE} == 'true' ]];then
	ARGS="enable ${SERVICE}"
else
	echo "Showing active units"
	ARGS=${DEFAULT_ARGS}
fi

echo "Executing:sudo systemctl ${ARGS}"
eval "sudo systemctl --no-legend ${ARGS}"

#-o --output=STRING     Change journal output mode (short, short-precise,
#                             short-iso, short-iso-precise, short-full,
#                             short-monotonic, short-unix,
#                             verbose, export, json, json-pretty, json-sse, cat)

