#!/usr/bin/zsh
#Inline ansi
BOLD="\033[1m"
ITALIC="\033[3m"
RESET="\033[m"
REVERSE="\033[7m"
STRIKE="\033[9m"
UNDER="\033[4m"

BLUE_FG="\033[34m"
CYAN_FG="\033[36m"
GREEN_FG="\033[32m"
MAGENTA_FG="\033[35m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"
YELLOW_FG="\033[33m"

read -r -d '' DESC<<EOF
Stop cupsd daemon, clear spool, restart daemon
EOF

if [[ ${1} == '-H' ]];then
	echo "Usage: ${0:t} [-H]"
	echo "${WHITE_FG}\nDESC${RESET}:${DESC}"
	exit
fi

echo -n "Restart cups daemon and clear spool? (y/n):"; read -q RESPONSE
[[ ${RESPONSE} == 'n' ]] && echo "\nOperation cancelled" && exit

sudo service cups stop
sudo rm -r /var/spool/cups
sudo service cups start

