#!/usr/bin/zsh
RESET="\033[m"
BOLD="\033[1m"
BLACK_FG="\033[30m"
BLACK_BG="\033[40m"
RED_FG="\033[1;31m"
RED_BG="\033[1;41m"
GREEN_FG="\033[1;32m"
GREEN_BG="\033[1;42m"
YELLOW_FG="\033[1;33m"
YELLOW_BG="\033[1;43m"
BLUE_FG="\033[1;34m"
BLUE_BG="\033[1;44m"
MAGENTA_FG="\033[1;35m"
MAGENTA_BG="\033[1;45m"
CYAN_FG="\033[1;36m"
CYAN_BG="\033[1;46m"
WHITE_FG="\033[1;37m"
WHITE_BG="\033[1;47m"

SCRIPT=$(basename ${0})

#Constants
typeset -a SOURCES=(/etc/apt/sources.list /etc/apt/sources.list.d) 
typeset -a PPAS=()

#Functions
add_ppa () {
	local PPA_ARG=$1

    [[ -z ${PPA_ARG} ]] && usage
	[[ ${DEBUG} == "true" ]] && echo "PPA_ARG:${PPA_ARG}"

    sudo add-apt-repository -y ${PPA_ARG} 
    RC=$?
	if [[ ${RC} -eq 0 ]];then
		echo "${GREEN_FG}Added:${WHITE_FG}${PPA_ARG}${RESET}"
		update-repo 
	else
		echo "${RED_FG}WARNING:${RESET} add-apt-repository returned non-zero exit status: ${RC}"
	fi
}

add_ppa_key () {
	local PPA_KEY=$1

    [[ -z ${PPA_KEY} ]] && usage
	[[ ${DEBUG} == "true" ]] && echo "PPA_KEY:${PPA_KEY}"

	sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys ${PPA_KEY}

    RC=$?
	if [[ ${RC} -eq 0 ]];then
		echo "${GREEN_FG}Added:${WHITE_FG}${PPA_KEY}${RESET}"
		update-repo 
	else
		echo "${RED_FG}WARNING:${RESET} apt-key returned non-zero exit status: ${RC}"
	fi
}

find_pkg () {
	local PKG_ARG=$1

	#optional arg 
	if [[ -n ${PKG_ARG} ]];then
		[[ ${DEBUG} == "true" ]] && echo "PKG_ARG:${PKG_ARG}"
    	PKG=${PKG_ARG}

	else
		PKG='*' 
	fi

    INSTALLED=($(dpkg-query --showformat='${Package}:${Status}\n' -W "*${PKG}*" | grep 'ok installed' | sed -e 's/:.*//g'))
    RC=$?
    [[ ${RC} -eq 0 ]] && for p in ${INSTALLED};do
        echo "${GREEN_FG}Installed Package${RESET}: ${p}"
        PPA=$(echo $(apt-cache policy ${p} | grep ' http') | cut -d\  -f2)
        [[ -z ${PPA} ]] && PPA=Unknown
        echo "${MAGENTA_FG}  Source${RESET}: ${WHITE_FG}${PPA}${RESET}"
    done
    UNINSTALLED=($(dpkg-query --showformat='${Package}:${Status}\n' -W "*${PKG}*" | grep -v 'ok installed' | sed -e 's/:.*//g'))
    for p in ${UNINSTALLED};do
        echo "${RED_FG}Uninstalled Package${RESET}: ${p}"
    done
}

find_ppa () {
	local PPA_ARG=$1

    [[ -z ${PPA_ARG} ]] && usage
	[[ ${DEBUG} == "true" ]] && echo "PPA_ARG:${PPA_ARG}"

	[[ ${PPA_ARG} =~ '/' ]] && echo "${WHITE_FG}PPA_ARG${RESET}:${SEARCHTERM} ${WHITE_FG}should be a keyword${RESET}; ${RED_FG}NOT${RESET} a pathname" && return 1

	for S in ${SOURCES};do
		if [[ -d ${S} ]];then
			LIST=("${(f)$(find ${S} -iname "*${PPA_ARG}*")}") 
			for L in ${LIST};do
				if [[ ${L:e} == "list" ]];then
					LINE=$(cat ${L} | grep -v '^#')
					if [[ ${LINE} =~ "launchpad" ]];then
						PPA=$(echo ${LINE} | sed -e 's#deb http://ppa.launchpad.net/##g' -e 's/[ ].*$//g')
					else
						PPA=$(echo ${LINE} | sed 's#.*//##g')
					fi
					[[ -n ${PPA} ]] && echo "${WHITE_FG}Source${RESET}: ${L}"
					[[ -n ${PPA} ]] && echo "${WHITE_FG}   PPA${RESET}: ppa:${PPA:h}"
					[[ -n ${LINE} ]] && echo "${WHITE_FG}   URL${RESET}: ${LINE}\n"
				fi
			done
			continue
		fi
		if [[ -f ${S} ]];then
			PPA_PATH=$(grep -i "${SEARCHTERM}" ${S} | grep -v '^#')
			[[ -n ${PPA_PATH} ]] && echo "${WHITE_FG}Source${RESET}:${S}"
			[[ -n ${PPA_PATH} ]] && echo ${PPA_PATH}

			continue
		fi
	done
}

list_ppa () {
	local PPA_ARG=$1
	local -A PPAS
	local ALL=false

	if [[ -n ${PPA_ARG} ]];then
		[[ ${DEBUG} == "true" ]] && echo "PPA_ARG:${PPA_ARG}"
		[[ ${DEBUG} == "true" ]] && echo "No PPA_ARG passed; listing sources matching ${PPA_ARG}"
	else
		[[ ${DEBUG} == "true" ]] && echo "No PPA_ARG passed; listing all sources..."
		ALL=true
	fi

	#build list of active ppas
	for S in ${SOURCES};do
		if [[ -d ${S} ]];then
			LIST=("${(f)$(find ${S})}") 
			for L in ${LIST};do
				if [[ ${L:e} == "list" ]];then
					FILE_CONTENT=("${(f)$(cat ${L})}")
					for LINE in ${FILE_CONTENT};do
						[[ ${LINE} =~ "^#" ]] && continue #ignore commented out 
						PPAS[${LINE}]=${L}

					done
				fi
			done
		else
			if [[ ${ALL} == "true" ]];then
				FILE_CONTENT=("${(f)$(cat ${S})}")
				for LINE in ${FILE_CONTENT};do
					[[ ${LINE} =~ "^#" ]] && continue #ignore commented out 
					PPAS[${LINE}]=${S}

				done
				HDR_LBL="All Active Sources\n------------------"
			else
				HDR_LBL="All Active Sources matching: ${PPA_ARG}\n---------------------------"
			fi
		fi
	done
	(
	echo "${BOLD}${WHITE_FG}${HDR_LBL}${RESET}"
	for P in ${(k)PPAS};do
		PPA=$(echo ${P} | grep -oP 'launchpad.net/\K.*?(?=/ubuntu)')
		if [[ -n ${PPA_ARG} ]];then
			echo ${PPA} | grep -qi ${PPA_ARG}

			[[ $? -ne 0 ]] && continue
		fi
		[[ -n ${PPA} ]] && PPA_LBL=${PPA} || PPA_LBL="${BOLD}${RED_FG}Not a Launchpad PPA${RESET} (possibly added manually)"

		echo ${P} | grep -qi 'universe\|multiverse\|restricted'
		[[ $? -eq 0 ]] && PPA_LBL="Distribution Source"

		[[ -n ${PPA} ]] && PPA_COLOR=${BOLD}${GREEN_FG} || PPA_COLOR=$WHITE_FG

		echo "\n${WHITE_FG}Source${RESET}: ${PPAS[${P}]}"
		echo "${WHITE_FG}   URL${RESET}: ${P}"
		echo "${WHITE_FG}   PPA${RESET}: ${PPA_COLOR}${PPA_LBL}${RESET}"
	done
	) | mypager
}

remove_ppa () {
	local PPA_ARG=$1

   [[ -z ${PPA_ARG} ]] && usage
	[[ ${DEBUG} == "true" ]] && echo "PPA_ARG:${PPA_ARG}"

	echo "${RED_FG}Removing${RESET}:${PPA_ARG}..."
   sudo add-apt-repository -r ${PPA_ARG}

   RC=$?
	[[ ${RC} -eq 0 ]] && echo "${RED_FG}Removed:${WHITE_FG}${1}${RESET}" || echo "${RED_FG}WARNING:${RESET} add-apt-repository returned non-zero exit status: ${RC}"
}

update-repo () {
	echo -n "Updating repository info..."
	sudo apt-get update 
    RC=$?
	[[ ${RC} -eq 0 ]] && echo "done." || echo "${RED_FG}WARNING:${RESET} apt-get update returned non-zero exit status: ${RC}"
}


#--Begin GetOpts--
RESET="\033[m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"

SCRIPT=${0:t}
parse_opts () {
	local OPTS=${@}
	local -a OPTSTRING
	local LETTER_OPT
	for O in {1..${#OPTS}};do
		[[ ${OPTS[${O}]} =~ '[a-z]' ]] && LETTER_OPT=${OPTS[${O}]}
		[[ ${O} -eq 1 && ${OPTS[${O}]} == ":" ]] && continue
		[[ ${O} -gt 1 && ${OPTS[${O}]} == ":" ]] && OPTSTRING+=$(opt_type ${LETTER_OPT}) && continue
		OPTSTRING+="-${OPTS[${O}]}"
	done
	echo ${OPTSTRING}
}

opt_type () {
	local OPT=${1}
	case ${OPT} in
		a) echo "<PPA>";;
		k) echo "<KEY>";;
		r) echo "<PPA>";;
		f) echo "<PACKAGE>";;
		l) echo "<PPA>";;
		p) echo "<PACKAGE>";;
	esac
}

usage () {
	local OPTS=$(parse_opts $OPTSTR)
	echo -e "\n${WHITE_FG}Usage${RESET}: $SCRIPT ${WHITE_FG}[${RESET} $OPTS ${WHITE_FG}]${RESET} <PPA>\n"
	echo -e "${WHITE_FG}-H${RESET} help"
	echo -e "${WHITE_FG}-D${RESET} debug"
	echo -e "${WHITE_FG}-a $(opt_type a)${RESET} Add PPA (default action)"
	echo -e "${WHITE_FG}-r $(opt_type r)${RESET} Remove PPA"
	echo -e "${WHITE_FG}-k $(opt_type k)${RESET} Add key"
	echo -e "${WHITE_FG}-f $(opt_type f)${RESET} Find source"
	echo -e "${WHITE_FG}-l $(opt_type l)${RESET} List PPA"
	echo -e "${WHITE_FG}-p $(opt_type p)${RESET} Find installed/uninstalled source"
	echo -e "${WHITE_FG}-u ${RESET} Update sources"
	echo -e "\n${WHITE_FG}DESC${RESET}:Description: Manage/show PPA repositories or show package with PPA\n"
	exit
}

OPTSTR=":DHa:r:f:l:p:k:u"

DEBUG=false
OPTIND=0
ADD_PPA=false
REMOVE_PPA=false
FIND_PPA=false
LIST_PPA=false
FIND_PKG=false
ADD_PPA_KEY=false

OPT_PASSED=false
while getopts ${OPTSTR} OPTION;do
	OPT_PASSED=true
	case $OPTION in
     H) usage;;
     D) DEBUG=true;;
     a) ADD_PPA=true;PPA_ARG=${OPTARG};;
     r) REMOVE_PPA=true;PPA_ARG=${OPTARG};;
     f) FIND_PPA=true;PPA_ARG=${OPTARG};;
     l) LIST_PPA=true;PPA_ARG=${OPTARG};;
     p) FIND_PKG=true;PKG_ARG=${OPTARG};;
     k) ADD_PPA_KEY=true;PPA_KEY=${OPTARG};;
     u) update-repo;exit;;
     :) if [[ ${OPTARG} == "l" ]];then
		 	LIST_PPA=true #optional option
			continue
     	elif [[ ${OPTARG} == "f" ]];then
		 	FIND_PKG=true #optional option
			continue
	 	else
			print -u2 "${SCRIPT}: option: -${OPTARG} requires an argument"
			usage
	 	fi;;
    \?) print -u2 "${SCRIPT}: unknown option -${OPTARG}"; usage;;
	esac
done
shift $((OPTIND -1))
#--End GetOpts--
 
#--Execution--

#set default action
if [[ ${OPT_PASSED} == "false" ]];then
	if [[ -n ${1} ]];then
		PPA_ARG=$1
		ADD_PPA=true #make default
	else
		usage
	fi
fi

[[ ${ADD_PPA} == "true" ]] && add_ppa ${PPA_ARG} && exit
[[ ${REMOVE_PPA} == "true" ]] && remove_ppa ${PPA_ARG} && exit
[[ ${FIND_PPA} == "true" ]] && find_ppa ${PPA_ARG} && exit
[[ ${LIST_PPA} == "true" ]] && list_ppa ${PPA_ARG} && exit
[[ ${FIND_PKG} == "true" ]] && find_pkg ${PKG_ARG} && exit
[[ ${ADD_PPA_KEY} == "true" ]] && add_ppa_key ${PPA_KEY} && exit

