#!/usr/bin/zsh

REVERSE=$(echo "\033[7m")
RESET=$(echo "\033[m")
BOLD=$(echo "\033[1m")
BLACK_FG=$(echo "\033[30m")
RED_FG=$(echo "\033[31m")
GREEN_FG=$(echo "\033[32m")
YELLOW_FG=$(echo "\033[1;33m")
BLUE_FG=$(echo "\033[34m")
MAGENTA_FG=$(echo "\033[1;35m")
CYAN_FG=$(echo "\033[36m")
WHITE_FG=$(echo "\033[37m")

(
cat <<EOF
The ${WHITE_FG}cron${RESET} command

   ${WHITE_FG}When             Setting${RESET}
   ${WHITE_FG}----             -------${RESET}
   Every 1 minute   ${WHITE_FG}*${RESET} ${GREEN_FG}*${RESET} ${MAGENTA_FG}*${RESET} ${RED_FG}*${RESET} ${CYAN_FG}*${RESET}
   Every 15 minutes ${WHITE_FG}*/15${RESET} ${GREEN_FG}*${RESET} ${MAGENTA_FG}*${RESET} ${RED_FG}*${RESET} ${CYAN_FG}*${RESET}
   Every 30 minutes ${WHITE_FG}*/30${RESET} ${GREEN_FG}*${RESET} ${MAGENTA_FG}*${RESET} ${RED_FG}*${RESET} ${CYAN_FG}*${RESET}
   Every 1 hour     ${WHITE_FG}0${RESET} ${GREEN_FG}*${RESET} ${MAGENTA_FG}*${RESET} ${RED_FG}*${RESET} ${CYAN_FG}*${RESET}
   Every 6 hours    ${WHITE_FG}0${RESET} ${GREEN_FG}*/6${RESET} ${MAGENTA_FG}*${RESET} ${RED_FG}*${RESET} ${CYAN_FG}*${RESET}
   Every 12 hours   ${WHITE_FG}0${RESET} ${GREEN_FG}*/12${RESET} ${MAGENTA_FG}*${RESET} ${RED_FG}*${RESET} ${CYAN_FG}*${RESET}
   Once a day       ${WHITE_FG}0${RESET} ${GREEN_FG}0${RESET} ${MAGENTA_FG}*${RESET} ${RED_FG}*${RESET} ${CYAN_FG}*${RESET}
   Once a week(SAT) ${WHITE_FG}0${RESET} ${GREEN_FG}0${RESET} ${MAGENTA_FG}*${RESET} ${RED_FG}*${RESET} ${CYAN_FG}SAT${RESET}
   Once a month     ${WHITE_FG}0${RESET} ${GREEN_FG}0${RESET} ${MAGENTA_FG}1${RESET} ${RED_FG}*${RESET} ${CYAN_FG}*${RESET}
   Weekdays 6pm     ${WHITE_FG}0${RESET} ${GREEN_FG}18${RESET} ${MAGENTA_FG}*${RESET} ${RED_FG}*${RESET} ${CYAN_FG}1-5${RESET}

   Here is a diagram of the general ${WHITE_FG}cron${RESET} syntax, for illustration:
   +---------------- ${WHITE_FG}minute (0-59)${RESET}
   |  +------------- ${GREEN_FG}hour (0-23)${RESET}
   |  |  +---------- ${MAGENTA_FG}day of month (1-31)${RESET}
   |  |  |  +------- ${RED_FG}month (1-12)${RESET}
   |  |  |  |  +---- ${CYAN_FG}day of week (0-6) (Sunday=0)${RESET}
   |  |  |  |  |
   ${WHITE_FG}*${RESET}  ${GREEN_FG}*${RESET}  ${MAGENTA_FG}*${RESET}  ${RED_FG}*${RESET}  ${CYAN_FG}*${RESET}  command to be executed

   In the following example, the ${WHITE_FG}cron${RESET} command shown below will activate the ${WHITE_FG}cron${RESET} tasks automatically on the hour:

   ${WHITE_FG}0 * * * * ping http://www.example.com${RESET}

   In the above sample, the ${WHITE_FG}0 * * * *${RESET} represents when the task should happen
   The first figure represents minutes i.e. on the "zero" minute, or top of the hour
   The other figures represent, respectively, hour, day, month and day of the week
   A * is a wildcard, meaning "every time" 
   The minimum is every one minute ${WHITE_FG}* * * * *${RESET}

   Thus, the ${WHITE_FG}cron${RESET} command example above means "ping http://www.example.com at the zero minute on every hour of every day
   of every month of every day of the week."
   
   Legend
   ------
   ${WHITE_FG}*${RESET}         Expands to all values for the field
   ${WHITE_FG},${RESET}         List separator
   ${WHITE_FG}-${RESET}         Range separator
   ${WHITE_FG}/${RESET}         Specifies step for ranges
   ${WHITE_FG}@hourly${RESET}   Run at the start of each hour
   ${WHITE_FG}@daily${RESET}    Run every day at midnight UTC
   ${WHITE_FG}@weekly${RESET}   Run at every Sunday at midnight UTC
   ${WHITE_FG}@monthly${RESET}  Run on the 1st of each month at midnight UTC
   ${WHITE_FG}@yearly${RESET}   Run on Jan 1st at midnight UTC
   ${WHITE_FG}@annually${RESET} Same as @yearly
   
   
   Every Minute                ${WHITE_FG}* * * * *${RESET}
   Every Five Minutes          ${WHITE_FG}*/5 * * * *${RESET}
   Every 10 Minutes            ${WHITE_FG}*/10 * * * *${RESET}
   Every 15 Minutes            ${WHITE_FG}*/15 * * * *${RESET}
   Every 30 Minutes            ${WHITE_FG}*/30 * * * *${RESET}
   Every Hour                  ${WHITE_FG}0 * * * *${RESET}
   Every Two Hours             ${WHITE_FG}0 */2 * * *${RESET}
   Every Six Hours             ${WHITE_FG}0 */6 * * *${RESET}
   Every 12 Hours              ${WHITE_FG}0 */12 * * *${RESET}
   During the Work Day         ${WHITE_FG}*/5 9-17 * * *${RESET}
   Every day at Midnight       ${WHITE_FG}0 0 * * *${RESET}
   Every Two Weeks             ${WHITE_FG}0 0 * * Sun [ \$(expr \$(date +%W) % 2) -eq 1 ] && /path/to/command${RESET}
   At the Start of Every Month ${WHITE_FG}0 0 1 * *${RESET}
   On January 1st at Midnight  ${WHITE_FG}0 0 1 1 * ${RESET}
   Weekends only               ${WHITE_FG}0 0 * * 6,0${RESET}
   
EOF
) | less -R
