#!/usr/bin/zsh
BOLD=$(echo -n "\033[1m")
ITALIC=$(echo -n "\033[3m")
RESET=$(echo -n "\033[m")
REVERSE=$(echo -n "\033[7m")
STRIKE=$(echo -n "\033[9m")
UNDER=$(echo -n "\033[4m")

BLACK_FG=$(echo -n "\033[30m")
BLUE_FG=$(echo -n "\033[34m")
CYAN_FG=$(echo -n "\033[36m")
GREEN_FG=$(echo -n "\033[32m")
MAGENTA_FG=$(echo -n "\033[35m")
RED_FG=$(echo -n "\033[31m")
WHITE_FG=$(echo -n "\033[37m")
YELLOW_FG=$(echo -n "\033[33m")

cat << EOF
${CYAN_FG}Command		Description${RESET}
mapadmin	Manage User Name Mapping for Microsoft Services for Network File System.
mount		Mount Network File System (NFS) network shares.
nfsadmin	Manage Server for NFS and Client for NFS.
nfsshare	Control Network File System (NFS) shares.
nfsstat		Display or reset counts of calls made to Server for NFS.
rpcinfo		List programs on remote computers.
showmount	Display mounted directories.
EOF
