#!/usr/bin/zsh

REVERSE=$(echo "\033[7m")
RESET=$(echo "\033[m")
BOLD=$(echo "\033[1m")
BLACK_FG=$(echo "\033[30m")
RED_FG=$(echo "\033[31m")
GREEN_FG=$(echo "\033[32m")
YELLOW_FG=$(echo "\033[1;33m")
BLUE_FG=$(echo "\033[34m")
MAGENTA_FG=$(echo "\033[1;35m")
CYAN_FG=$(echo "\033[36m")
WHITE_FG=$(echo "\033[37m")

(
cat <<EOF
Rsync – To Slash or Not To Slash?

Without a slash, copy the hierarchy ${WHITE_FG}including${RESET} top level directory
With a slash, copy the hierarchy ${WHITE_FG}below${RESET} the top level directory

If we take the following as the source directory:

$ tree testing

testing
|-- another
|   |-- wilma
|-- betty
|-- fred
|-- nested
    |-- barney

The destination is an empty directory named test_backup.

${WHITE_FG}No Slashes${RESET}
The first test has no slashes on any of the directories.

$ rsync --archive --recursive testing ${CYAN_FG}test_backup${RESET}
$ tree test_backup

test_backup
|${WHITE_FG}--testing${RESET}
   |-- another
   |   |-- wilma
   |-- betty
   |-- fred
   |-- nested
       |-- barney

You can see that the ${WHITE_FG}whole hierarchy${RESET} of the testing directory has been
recreated within the destination directory.

${WHITE_FG}Slash on Source${RESET}
$ rsync --archive --recursive ${CYAN_FG}testing/${RESET} test_backup
$ tree test_backup

test_backup
|${WHITE_FG}-- another${RESET}
|   |-- wilma
|-- betty
|-- fred
|-- nested
    |-- barney

This is different. The contents of the source directory have been duplicated into the destination
directory.

As to slashes following the destination, if the source is a file ${WHITE_FG}and destination doesn't exist${RESET}
— this will make a copy of SRC called DEST:

rsync SRC DEST

, whereas, with a slash, this will create directory DEST and copy the SRC file into it:

rsync SRC DEST/
EOF
) | less -R
