#!/usr/bin/zsh
RESET="\033[m"
RED_FG="\033[31m"
GREEN_FG="\033[32m"
YELLOW_FG="\033[33m"
BLUE_FG="\033[34m"
MAGENTA_FG="\033[35m"
CYAN_FG="\033[36m"
WHITE_FG="\033[37m"
BOLD="\033[1m"

E_RESET=$(echo -n "\033[m")
E_GREEN_FG=$(echo -n "\033[32m")
E_RED_FG=$(echo -n "\033[31m")
E_MAGENTA_FG=$(echo -n "\033[35m")

#Constants
ZPATH=/usr/share/zoneinfo
DIR=/usr/share/zoneinfo
EXCLUDE="${DIR:t}|posix|right|SystemV|Etc"

LOCAL_TIME=$(date +"%T")
LOCAL_DATE=$(date +"%D")
LOCAL_ZONE=$(date +"%Z")

UTC_TIME=$(date -u +"%T")
UTC_DATE=$(date -u +"%D")
UTC_HOUR=$(date -u +"%H")
UTC_DIFF=$(date +"%z")

#Definitions
typeset -a TZ=(Los_Angeles Denver Chicago New_York)
typeset -U ZONES
typeset -a LIST
typeset -i HOUR_DIFF
typeset -i UTC_DIFF_VAL

#Functions
function rep () {
	local CHAR=${1}
	local LENGTH=${2}
	LINE=''
	for ((x=0;x < ${LENGTH};x++));do
		LINE=${LINE}''${CHAR}
	done
	echo ${LINE}
}

function list () {
	LIST=($(find ${DIR} -maxdepth 1))
	for L in ${LIST};do
		if [[ -d ${L} && ! ${L:t} =~ ${EXCLUDE} ]];then
			echo "\n"
			HDR="${L:t}:"
			echo ${WHITE_FG}${HDR}${RESET}
			echo $(rep - ${#HDR})
			/bin/ls ${L}
		fi
	done
}

#--Begin GetOpts--
RESET="\033[m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"

SCRIPT=${0:t}
function parse_opts {
	local OPTS=$@
	local -a OPTSTRING
	for O in {1..${#OPTS}};do
		[[ $O -eq 1 && ${OPTS[$O]} == ":" ]] && continue
		[[ $O -gt 1 && ${OPTS[$O]} == ":" ]] && OPTSTRING+="<PARAM>" && continue
		OPTSTRING+="-${OPTS[$O]}"
	done
	echo $OPTSTRING
}

function usage {
	local OPTS=$(parse_opts $OPTSTR)
	echo -e "\n${WHITE_FG}Usage${RESET}: $SCRIPT ${WHITE_FG}[${RESET} $OPTS ${WHITE_FG}]${RESET} <PARAM>\n"
	echo -e "${WHITE_FG}-H${RESET} help"
	echo -e "${WHITE_FG}-D${RESET} debug"
	echo -e "${WHITE_FG}-l${RESET} list zones"
	echo -e "\n${WHITE_FG}DESC${RESET}:Show times in other zones. Accepts TZ id as an argument.  Default is USA TZ's\n"
	exit
}

OPTSTR=":HDl"

DEBUG=false
OPTIND=0
while getopts ${OPTSTR} OPTION;do
	case $OPTION in
     H) usage;;
     D) DEBUG=true;;
     l) list;;
     :) print -u2 "${SCRIPT}: option: -${OPTARG} requires an argument"; usage;;
    \?) print -u2 "${SCRIPT}: unknown option -${OPTARG}"; usage;;
	esac
done
shift $((OPTIND -1))
#--End GetOpts--

#--Execution--
[[ -n $1 ]] && TZ=$1

for Z in ${TZ};do
	LIST+=($(find ${ZPATH} -iname "*${Z}*"))
	[[ -z ${LIST[1]} ]] && echo "${RED_FG}Error${RESET}:No time zone(s) matching ${WHITE_FG}[${RESET} ${BOLD}${TZ}${RESET} ${WHITE_FG}]${RESET} were found" && exit
done

for Z in ${LIST};do
	DEPTH=$(echo ${Z#${ZPATH}} | grep -o '/' | wc -l)
	if [[ ${DEPTH} -gt 2 && -z ${Z:e} ]];then
		ZONES+=($(echo ${Z} | rev| cut -d'/' -f -2 | rev))
	fi
done

UTC_DIFF_VAL=$(date +"%:::z")

[[ ${UTC_DIFF} =~ "^\+" ]] && UTC_LBL="ahead" || UTC_LBL="behind"
[[ ${UTC_DIFF_VAL} -eq 1 ]] && HP='' || HP='s'

if [[ ${DEBUG} == "true" ]];then
	echo "--> LOCAL_TIME:${LOCAL_TIME}"
	echo "--> UTC_DIFF:${UTC_DIFF}"
	echo "--> UTC_DIFF_VAL:${UTC_DIFF_VAL}"
	echo "--> UTC_LBL:${UTC_LBL}"
	echo "--> UTC_TIME:${UTC_TIME}"
fi

echo "LOCAL:${WHITE_FG}${LOCAL_TIME} ${CYAN_FG}${LOCAL_ZONE}${RESET} ${LOCAL_DATE}"
echo "  UTC:${WHITE_FG}${UTC_TIME}${RESET} ${UTC_DATE} (${UTC_DIFF_VAL} hour${HP} ${UTC_LBL})\n"

#typeset -i TZ_DIFF

for Z in ${ZONES};do
	TZ_HEAD=$(TZ=${Z} date +"%A, %B %d %Y,")
	TZ_DATE=$(TZ=${Z} date +"%D")
	TZ_TIME=$(TZ=${Z} date +"%I:%M")
	TZ_AMPM=$(TZ=${Z} date +"%p")
	TZ_TAIL=$(TZ=${Z} date +"%Z")
	TZ_DIFF=$(TZ=${Z} date +"%z")

	[[ ${TZ_AMPM} == "AM" ]] && TZ_AMPM="${E_GREEN_FG}${TZ_AMPM}${E_RESET}" || TZ_AMPM="${E_RED_FG}${TZ_AMPM}${E_RESET}"

	if [[ ${DEBUG} == "true" ]];then
		echo "--> TZ_AMPM=${TZ_AMPM}"
		echo "--> TZ_DATE=${TZ_DATE}"
		echo "--> TZ_DIFF=${TZ_DIFF}"
		echo "--> TZ_HEAD=${TZ_HEAD}"
		echo "--> TZ_TAIL=${TZ_TAIL}"
		echo "--> TZ_TIME=${TZ_TIME}"
		echo "--> UTC_DIFF:${UTC_DIFF}"
	fi
	
	TZ_DIFF_VAL=${TZ_DIFF[1,3]}
	UTC_DIFF_VAL=${UTC_DIFF[1,3]}
	(( HOUR_DIFF = TZ_DIFF_VAL - UTC_DIFF_VAL ))

	if [[ ${DEBUG} == "true" ]];then
		echo "--> HOUR_DIFF = ${TZ_DIFF_VAL} - ${UTC_DIFF_VAL}"
		echo "--> HOUR_DIFF:${HOUR_DIFF}"
		echo "--> TZ_DIFF_VAL:${TZ_DIFF_VAL}"
		echo "--> UTC_DIFF_VAL:${UTC_DIFF_VAL}"
	fi

	if [[ ${HOUR_DIFF} -gt 0 ]];then
		HOUR_LBL="behind"
	elif [[ ${HOUR_DIFF} -lt 0 ]];then
		HOUR_LBL="ahead"
	fi

	if [[ ${DEBUG} == "true" ]];then
		echo "--> HOUR_LBL:${HOUR_LBL}"
		echo "--> TZ_DIFF_VAL:${TZ_DIFF_VAL} UTC_DIFF_VAL:${UTC_DIFF_VAL}"
	fi

	[[ ${TZ_DIFF} =~ "^-" ]] && (( HOUR_DIFF = TZ_DIFF_VAL - UTC_DIFF_VAL )) && HOUR_DIFF=$(echo ${HOUR_DIFF} | tr -d -) && DIFF_LBL="You [${E_MAGENTA_FG}${LOCAL_ZONE}${E_RESET}] are ${HOUR_DIFF} hours ${HOUR_LBL}"
	[[ ${TZ_DIFF} =~ "^\+" ]] && (( HOUR_DIFF = TZ_DIFF_VAL - UTC_DIFF_VAL )) && DIFF_LBL="You [${E_MAGENTA_FG}${LOCAL_ZONE}${E_RESET}] are ${HOUR_DIFF} hours ${HOUR_LBL}"
	[[ ${HOUR_DIFF} -lt 0 ]] && HOUR_DIFF=$(echo ${HOUR_DIFF} | tr -d -) && DIFF_LBL="You [${E_MAGENTA_FG}${LOCAL_ZONE}${E_RESET}] are ${HOUR_DIFF} hours ${HOUR_LBL}"
	[[ ${HOUR_DIFF} -eq 0 ]] && DIFF_LBL="You [${E_MAGENTA_FG}${LOCAL_ZONE}${E_RESET}] have the same time"
	[[ ${HOUR_DIFF} -eq 1 ]] && DIFF_LBL=$(echo ${DIFF_LBL} | sed 's/hours/hour/g')

	printf "In the ${WHITE_FG}%20s${RESET} ${CYAN_FG}%3s${RESET} time zone it is %20s at ${WHITE_FG}%5s${RESET} %2s (%s)\n" ${Z} ${TZ_TAIL} ${TZ_HEAD} ${TZ_TIME} ${TZ_AMPM} ${DIFF_LBL}
done
