#!/usr/bin/zsh
RESET="\033[m"
RED_FG="\033[31m"
GREEN_FG="\033[32m"
YELLOW_FG="\033[33m"
BLUE_FG="\033[34m"
MAGENTA_FG="\033[35m"
CYAN_FG="\033[36m"
WHITE_FG="\033[37m"
BOLD="\033[1m"

echo "wmctrl Info\n-------------------"
wmctrl -m
echo "\nPlain window list\n-------------------"
wmctrl -l
echo "\nWindow list w/PID\n-------------------"
wmctrl -lp
echo "\nWindow list w/Group\n-------------------"
wmctrl -lG
echo "\nWindow list w/Class\n-------------------"
wmctrl -lx
echo "\nDesktops\n-------------------"
wmctrl -d
