#!/usr/bin/zsh
RESET="\033[m"
RED_FG="\033[31m"
GREEN_FG="\033[32m"
YELLOW_FG="\033[33m"
BLUE_FG="\033[34m"
MAGENTA_FG="\033[35m"
CYAN_FG="\033[36m"
WHITE_FG="\033[37m"

WDW_LIST=("${(f)$( wmctrl -l | grep -i terminal)}") 
for W in ${WDW_LIST};do
	WIN_ID=$(echo ${W} | cut -d' ' -f1)
	xprop -id ${WIN_ID} | grep -qi focused
	[[ ${?} -eq 0 ]] && echo ${W} 
done
