#!/usr/bin/zsh
exec /opt/google/chrome/google-chrome --app=https://web.whatsapp.com &
while true;do
	WDW_ID=$(wmctrl -l | grep -i whatsapp | tr -s '[:space:]' | cut -d' ' -f1)
	if [[ -n ${WDW_ID} ]];then
		wmctrl -i -r ${WDW_ID} -b toggle,maximized_vert,maximized_horz
		sleep .5
		wmctrl -i -r ${WDW_ID} -b toggle,maximized_vert,maximized_horz
		break
	fi
	sleep 1
done
