#!/usr/bin/zsh

#vim: syntax off
RESET="\033[m"
BOLD="\033[1m"
ITALIC="\033[3m"
UNDER="\033[4m"
REVERSE="\033[7m"
STRIKE="\033[9m"

BLACK_FG="\033[30m"
RED_FG="\033[31m"
GREEN_FG="\033[32m"
YELLOW_FG="\033[33m"
BLUE_FG="\033[34m"
MAGENTA_FG="\033[35m"
CYAN_FG="\033[36m"
WHITE_FG="\033[37m"

#Constants
COLORS=/usr/local/etc/color.template
HEADERS=/usr/local/etc/app.template
GETOPTS=/usr/local/etc/getopt.template
CURSOR=/usr/local/etc/list_cursor.template
_LIB=/usr/local/lib
_DIR_USER=$(id -nu)
_DIR_GROUP=$(id -ng)

#Imports
source ${_LIB}/common.zsh

#Declarations
typeset -a FILES

#Functions
is_file_editable () {
	local FILE=${1}
	local USER=$(id -nu)
	local GROUP=$(id -ng)
	local FILE_USER
	local FILE_GROUP
	local USER_PERMS
	local GROUP_PERMS
	local NEW_FILE

	[[ ${DEBUG} == "true" ]] && echo "is_file_editable:FILE ARG:${WHITE_FG}${FILE}${RESET}" >&2
	[[ ${DEBUG} == "true" ]] && echo "is_file_editable:DIRECTORY:${WHITE_FG}${FILE:h}${RESET}" >&2
	[[ ${DEBUG} == "true" ]] && echo "is_file_editable:FILE:${WHITE_FG}${FILE:t}${RESET}" >&2
	[[ ! -e ${FILE} ]] && NEW_FILE=true || NEW_FILE=false

	if [[ ${DEBUG} == "true" ]];then
		if [[ ${NEW_FILE} == "true" ]];then
			echo "is_file_editable evaluated:FILE:${WHITE_FG}${FILE:t}${RESET} is a ${GREEN_FG}NEW file${RESET}" >&2
		else
			echo "is_file_editable evaluated:FILE:${WHITE_FG}${FILE:t}${RESET} is an ${RED_FG}EXISTING file${RESET}" >&2
		fi
	fi

	[[ ${DEBUG} == "true" ]] && echo "is_file_editable evaluated:CURRENT USER:${WHITE_FG}${USER}${RESET}" >&2
	[[ ${DEBUG} == "true" ]] && echo "is_file_editable evaluated:CURRENT GROUP:${WHITE_FG}${GROUP}${RESET}" >&2

	if [[ ${NEW_FILE} == "true" ]];then
		[[ ${DEBUG} == "true" ]] && echo "is_file_editable:new file -  checking directory permissions" >&2
		FILE_USER=$(stat -c '%U' ${FILE:h} 2>/dev/null)
		FILE_GROUP=$(stat -c '%G' ${FILE:h} 2>/dev/null)
		USER_PERMS=$(stat -c '%a' ${FILE:h} 2>/dev/null)
		GROUP_PERMS=$(stat -c '%a' ${FILE:h} 2>/dev/null)
		[[ ${DEBUG} == "true" ]] && echo "is_file_editable evaluated:DIR_USER:${WHITE_FG}${FILE_USER}${RESET}" >&2
		[[ ${DEBUG} == "true" ]] && echo "is_file_editable evaluated:DIR_GROUP:${WHITE_FG}${FILE_GROUP}${RESET}" >&2
	else
		FILE_USER=$(stat -c '%U' ${FILE} 2>/dev/null)
		FILE_GROUP=$(stat -c '%G' ${FILE} 2>/dev/null)
		USER_PERMS=$(stat -c '%a' ${FILE} 2>/dev/null)
		GROUP_PERMS=$(stat -c '%a' ${FILE} 2>/dev/null)
		[[ ${DEBUG} == "true" ]] && echo "is_file_editable evaluated:FILE_USER:${WHITE_FG}${FILE_USER}${RESET}" >&2
		[[ ${DEBUG} == "true" ]] && echo "is_file_editable evaluated:FILE_GROUP:${WHITE_FG}${FILE_GROUP}${RESET}" >&2
	fi

	if [[ ${USER} == ${FILE_USER} && ${USER_PERMS} =~ '^[76].' ]];then
		[[ ${DEBUG} == "true" ]] && echo "is_file_editable evaluated:USER:${USER} == FILE_USER:${FILE_USER} ${GREEN_FG}not using sudo${RESET}" >&2
		return 0
	elif [[ ${GROUP} == "${FILE_GROUP}" && ${GROUP_PERMS} =~ '^.[76]' ]];then
		[[ ${DEBUG} == "true" ]] && echo "is_file_editable evaluated:GROUP:${GROUP} == FILE_GROUP:${FILE_GROUP} ${GREEN_FG}not using sudo${RESET}" >&2
		return 0
	else
		[[ ${DEBUG} == "true" ]] && echo "is_file_editable evaluated:No matching permissions for group or user - ${RED_FG}not editable without sudo${RESET}" >&2
		return 1
	fi
}

make_zsh () {
	local FN=${1}

	case ${MAKE_TYPE} in
		ZSH_LIST)	echo '#!/usr/bin/zsh' > ${FN}
						cat ${COLORS} >> ${FN} 
						cat ${CURSOR} >> ${FN} 
						;;
		ZSH_FULL)	echo '#!/usr/bin/zsh' > ${FN}
						cat ${COLORS} >> ${FN} 
						echo >> ${FN}
						cat ${HEADERS} >> ${FN} 
						echo >> ${FN}
						cat ${GETOPTS} >> ${FN} 
						echo >> ${FN}
						;;
		  ZSH)		echo '#!/usr/bin/zsh' > ${FN}
						cat ${COLORS} >> ${FN} 
						;;
	esac
}

make_perl () {
	local FN=${1}

	echo '#!/usr/bin/env perl' > ${FN}
	echo 'use warnings;'>> ${FN}
	echo 'use strict;'>> ${FN}
	echo 'use diagnostics;'>> ${FN}
}

make_python () {
	local FN=${1}

	echo '#!/usr/bin/env python' > ${FN}
}

#--Begin GetOpts--
RESET="\033[m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"

read -r -d '' DESC<<EOF
Frontend for vi with added features
EOF


opt_type () {
	local OPT=${1}
	case ${OPT} in
		f) echo "<FILE>";;
	esac
}

function parse_opts {
	local OPTS=${@}
	local -a OPTSTRING
	local O

	for O in {1..${#OPTS}};do
		[[ ${O} -eq 1 && ${OPTS[${O}]} == ":" ]] && continue
		[[ ${O} -gt 1 && ${OPTS[${O}]} == ":" ]] && OPTSTRING+="<PARAM>" && continue
		OPTSTRING+="-${OPTS[${O}]}"
	done
	echo ${OPTSTRING}
}

SCRIPT=vi
usage () {
	local OPTS=$(parse_opts ${OPTSTR})
	local -a PENDING_MSGS=(${@})

	tabs 5
	[[ ${_SMCUP} == 'true' ]] && do_rmcup

	echo -e "\n${WHITE_FG}Usage${RESET}: ${SCRIPT} ${OPTS} $(opt_type f)\n"
	echo -e "${WHITE_FG}-H${RESET} help"
	echo -e "${WHITE_FG}-D${RESET} debug"
	echo -e "${WHITE_FG}-A${RESET} create scrollable list stub"
	echo -e "${WHITE_FG}-E${RESET} create enhanced zsh shell script stub"
	echo -e "${WHITE_FG}-P${RESET} create python script"
	echo -e "${WHITE_FG}-e${RESET} create zsh script"
	echo -e "${WHITE_FG}-p${RESET} create perl script"
	echo -e "\n${WHITE_FG}DESC${RESET}:${DESC}"

	exit_leave ${PENDING_MSGS}
}

OPTSTR=":HDAEPep"

DEBUG=false
MAKE_SCRIPT=false
ZSH_SCRIPT=false
PERL_SCRIPT=false
PYTHON_SCRIPT=false
OPTIND=0

while getopts ${OPTSTR} OPTION;do
	case ${OPTION} in
     H) usage;;
     D) DEBUG=true;;
     A) MAKE_SCRIPT=true;MAKE_TYPE=ZSH_LIST;;
     E) MAKE_SCRIPT=true;MAKE_TYPE=ZSH_FULL;;
     P) MAKE_SCRIPT=true;MAKE_TYPE=PYTHON;;
     e) MAKE_SCRIPT=true;MAKE_TYPE=ZSH;;
     p) MAKE_SCRIPT=true;MAKE_TYPE=PERL;;
     :) print -u2 "${SCRIPT}: option: -${OPTARG} requires an argument"; usage;;
    \?) print -u2 "${SCRIPT}: unknown option -${OPTARG}"; usage;;
	esac
done

shift $((OPTIND -1))
#--End GetOpts--

#--Execution--
FILES=(${@})
SIZE=0

[[ ${#} -eq 0 ]] && usage $(msg_err "Missing arg:$(opt_type f)")
[[ ${#FILES} -gt 1 && ${MAKE_SCRIPT} == "true" ]] && usage $(msg_err "Only one file name allowed for make script option")

#check file list
for F in ${FILES};do
	if [[ -n ${F} ]];then
		is_file_editable ${F}
		RC=${?}
		[[ ${DEBUG} == "true" ]] && echo "is_file_editable returned:${RC}" >&2
		if [[ ${RC} -eq 0 ]];then
			USE_SUDO=true
			break
		else
			USE_SUDO=false
		fi
	fi
done

if [[ ${#FILES} -eq 1 ]];then
	if [[ ${MAKE_SCRIPT} == "true" ]];then
		if [[ ! -e ${F} ]];then #ignore for existing files
			[[ ${MAKE_TYPE} =~ "ZSH" ]] && make_zsh ${F}
			[[ ${MAKE_TYPE} == "PERL" ]] && make_perl ${F}
			[[ ${MAKE_TYPE} == "PYTHON" ]] && make_python ${F}
			SIZE=$(stat -c '%s' ${F} 2>/dev/null)
			if [[ -e ${F} ]];then
				sudo chmod 755 ${F}
				sudo chown ${_DIR_USER}:${_DIR_GROUP} ${F}
			fi
		else
			echo "FILE:${F} exists - editing existing file"
			echo "Press any key..."; read
		fi
	fi
fi

if [[ ${RC} -ne 0 ]];then
	[[ ${DEBUG} == "true" ]] && echo "sudo will be used" >&2 && exit
	sudo -E /usr/bin/vim ${FILES} && clear
else
	[[ ${DEBUG} == "true" ]] && echo "sudo will NOT be used" >&2 && exit
	/usr/bin/vim ${FILES} && clear
fi
	
if [[ ${#FILES} -eq 1 ]];then
	#post process cleanup
	if [[ ${MAKE_SCRIPT} == "true" && ${MAKE_TYPE} != 'ZSH_FULL' ]];then
		if [[ -e ${F} ]];then
			if [[ $(stat -c '%s' ${F} 2>/dev/null) == ${SIZE} ]];then
				echo "${F} was abandoned. Removing..."
				rm -f ${F} #rm if file was abandoned
			fi
		fi
	fi
fi

exit_leave
