#!/usr/bin/zsh
RESET="\033[m"
RED_FG="\033[31m"
GREEN_FG="\033[32m"
YELLOW_FG="\033[33m"
BLUE_FG="\033[34m"
MAGENTA_FG="\033[35m"
CYAN_FG="\033[36m"
WHITE_FG="\033[37m"

[[ ${#} -eq 0 ]] && echo "${0:t} ${RED_FG}Missing arguments${RESET}" && exit

ARGLIST=(${@})

echo "${GREEN_FG}Updating locate db${RESET}" && sudo updatedb 2>/dev/null

echo "locate ${ARGLIST}"
locate ${ARGLIST} 
